#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │      Compiling Functions contracts...        │"
echo " └──────────────────────────────────────────────┘"

PROJECT="functions"

CONTRACTS_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../ && pwd -P )"

export FOUNDRY_PROFILE="$PROJECT"

compileContract () {
  local contract
  contract=$(basename "$1")
  echo "Compiling" "$contract"

  local command
  command="forge build $CONTRACTS_DIR/src/v0.8/$PROJECT/"$1.sol" \
   --root $CONTRACTS_DIR \
   --extra-output-files bin abi \
   -o $CONTRACTS_DIR/solc/$PROJECT/$contract"
   $command

   # Copy the generated abi files to a single folder
   mkdir -p "$CONTRACTS_DIR"/abi/v0.8/"$PROJECT"
   cp "$CONTRACTS_DIR"/solc/$PROJECT/"$contract"/"$contract".sol/"$contract".abi.json "$CONTRACTS_DIR"/abi/v0.8/"$PROJECT"/"$contract".abi.json
}

############################
# Version 1 (Mainnet Preview)
############################

compileContract v1_3_1/libraries/FunctionsRequest
compileContract v1_3_1/FunctionsClient
compileContract v1_3_1/FunctionsRouter
compileContract v1_3_1/FunctionsCoordinator
compileContract v1_3_1/accessControl/TermsOfServiceAllowList
compileContract v1_3_1/example/FunctionsClientExample

# Test helpers
compileContract tests/v1_3_1/testhelpers/FunctionsCoordinatorTestHelper
compileContract tests/v1_3_1/testhelpers/FunctionsLoadTestClient

# Mocks
compileContract v1_3_1/mocks/FunctionsV1EventsMock
