#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │          Compiling shared contracts...       │"
echo " └──────────────────────────────────────────────┘"

PROJECT="shared"
FOUNDRY_PROJECT_SUFFIX=""

CONTRACTS_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../ && pwd -P )"
export FOUNDRY_PROFILE="$PROJECT"$FOUNDRY_PROJECT_SUFFIX

SOLC_VERSION_DEFAULT="0.8.19"
SOLC_VERSION_026="0.8.26"

compileContractWithVersion() {
  local path="$1"
  local version="$2"

  local contract
  contract=$(basename "$path")
  echo "Compiling" "$contract"

  local current_project="$PROJECT"
  if [ -n "$3" ]; then
    echo "Compiling from another project: ""$3"
    current_project=$3
  fi

  # Build base command
  local command
  command="forge build $CONTRACTS_DIR/src/v0.8/$current_project/"$path.sol" \
   --root $CONTRACTS_DIR \
   --extra-output-files bin abi"

  # Add version if provided
  if [ -n "$version" ]; then
    command="$command \
   --use $version"
  fi

  # Output directory
  command="$command \
   -o $CONTRACTS_DIR/solc/$PROJECT/$contract"

  $command
}

compileContract() {
  compileContractWithVersion "$1" "$SOLC_VERSION_DEFAULT" "$2"
}

compileContractWithSolc826() {
  compileContractWithVersion "$1" "$SOLC_VERSION_026" "$2"
}

compileContract interfaces/AggregatorV3Interface
compileContract interfaces/ITypeAndVersion
compileContract token/ERC677/ERC677
compileContract token/ERC677/BurnMintERC677
compileContract token/ERC677/LinkToken
compileContract token/ERC20/BurnMintERC20

compileContractWithSolc826 token/ERC20/upgradeable/BurnMintERC20PausableFreezableTransparent
compileContractWithSolc826 token/ERC20/upgradeable/BurnMintERC20PausableFreezableUUPS
compileContractWithSolc826 token/ERC20/upgradeable/BurnMintERC20PausableTransparent
compileContractWithSolc826 token/ERC20/upgradeable/BurnMintERC20PausableUUPS
compileContractWithSolc826 token/ERC20/upgradeable/BurnMintERC20Transparent
compileContractWithSolc826 token/ERC20/upgradeable/BurnMintERC20UUPS
compileContractWithSolc826 token/ERC20/upgradeable/IBurnMintERC20Upgradeable

compileContract test/helpers/BurnMintERC20WithDrip
compileContract test/helpers/ChainReaderTester
compileContract test/helpers/LogEmitter
compileContract test/helpers/VRFLogEmitter
compileContract mocks/MockV3Aggregator
compileContract mocks/WERC20Mock
compileContract token/ERC20/zksync/WETH9ZKSync

compileContract ERC20 ../../node_modules/@openzeppelin/contracts@4.8.3/token/ERC20
compileContract multicall/ebd8b64/src/Multicall3 vendor
compileContract canonical-weth/WETH9 vendor
