#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │      Compiling L2EP contracts...             │"
echo " └──────────────────────────────────────────────┘"

PROJECT="l2ep"

CONTRACTS_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../ && pwd -P )"
export FOUNDRY_PROFILE="$PROJECT"

compileContract () {
  local contract
  contract=$(basename "$1")
  echo "Compiling" "$contract"

  dir=$CONTRACTS_DIR/solc/$PROJECT/$contract

  local command
  command="forge build $CONTRACTS_DIR/src/v0.8/$PROJECT/"$1.sol" \
       --root $CONTRACTS_DIR \
       --extra-output-files bin abi metadata \
       --build-info \
       --build-info-path $dir/build \
       -o $dir"

  $command

  mv $(find $dir/build -type f -name '*.json' ! -name 'build.json') $dir/build/build.json


  # Copy the generated abi files to a single folder
  mkdir -p "$CONTRACTS_DIR"/abi/v0.8/"$PROJECT"
  cp "$dir"/"$contract".sol/"$contract".abi.json "$CONTRACTS_DIR"/abi/v0.8/"$PROJECT"/"$contract".abi.json
}

compileContract arbitrum/ArbitrumValidator
compileContract arbitrum/ArbitrumSequencerUptimeFeed
compileContract arbitrum/ArbitrumCrossDomainForwarder
compileContract arbitrum/ArbitrumCrossDomainGovernor

compileContract optimism/OptimismValidator
compileContract optimism/OptimismSequencerUptimeFeed
compileContract optimism/OptimismCrossDomainForwarder
compileContract optimism/OptimismCrossDomainGovernor

compileContract scroll/ScrollValidator
compileContract scroll/ScrollSequencerUptimeFeed
compileContract scroll/ScrollCrossDomainForwarder
compileContract scroll/ScrollCrossDomainGovernor
