#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │          Compiling ZKSync contracts...       │"
echo " └──────────────────────────────────────────────┘"

FOUNDRY_PROJECT_SUFFIX=""
CONTRACTS_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../ && pwd -P )"

compileContract() {
  local contract
  contract=$(basename "$1")
  echo "Compiling" "$contract"

  PROJECT=$2
  export FOUNDRY_PROFILE="$PROJECT"$FOUNDRY_PROJECT_SUFFIX

  ${CONTRACTS_DIR}/../tools/bin/forge_zksync build $CONTRACTS_DIR/src/v0.8/$PROJECT/"$1.sol" --zksync \
   --root $CONTRACTS_DIR \
   $3
}

compileContract token/ERC677/LinkToken shared "--use 0.8.19"
compileContract token/ERC677/BurnMintERC677 shared "--use 0.8.19"
compileContract multicall/ebd8b64/src/Multicall3 vendor "--use 0.8.19"
compileContract CapabilitiesRegistry keystone

# simplest way without modifications to list all ccip contracts
for x in $(grep "^compileContract .*$" ${CONTRACTS_DIR}/scripts/native_solc_compile_all_ccip | sed 's/compileContract //'); do \
  compileContract $x ccip; \
done
