[profile.default]
evm_version = 'paris'
optimizer = true
via_ir = true
out = 'foundry-artifacts'
cache_path = 'foundry-cache'
libs = ['node_modules']
bytecode_hash = "none"
ffi = false
deny_warnings = true

# default is zero, using a non-zero amount enables us to test e.g. billing based on gas prices.
gas_price = 1
block_timestamp = 1234567890
block_number = 12345

[profile.v1]
optimizer_runs = 1_000_000
solc_version = '0.8.24'
src = 'src/v1'
test = 'src/v1/test'

[profile.v2]
optimizer_runs = 1_000
solc_version = '0.8.26'
src = 'src/v2'
test = 'src/v2/test'

[profile.dev]
optimizer_runs = 1_000_000
solc_version = '0.8.24'
src = 'src/dev'
test = 'src/dev/test'
via_ir = false

[fmt]
tab_width = 2
multiline_func_header = "params_first"
sort_imports = true
single_line_statement_blocks = "preserve"
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[lint]
lint_on_build = false