// SPDX-License-Identifier: BUSL 1.1
pragma solidity 0.8.26;

import {Ownable2StepMsgSender} from "../../../shared/access/Ownable2StepMsgSender.sol";

import {ECDSA} from "../../../vendor/openzeppelin-solidity/v5.0.2/contracts/utils/cryptography/ECDSA.sol";
import {MessageHashUtils} from
  "../../../vendor/openzeppelin-solidity/v5.0.2/contracts/utils/cryptography/MessageHashUtils.sol";
import {EnumerableSet} from "../../../vendor/openzeppelin-solidity/v5.0.2/contracts/utils/structs/EnumerableSet.sol";

/// @title OwnershipLink
/// @notice This contract allows transaction senders to submit ownership proofs for linking and unlinking owner address.
/// @dev Ownership proofs are signed messages generated by a trusted entity, with each proof being unique for each owner
/// address. The owner address is embedded into the proof itself together with other relevant metadata that uniquely
/// represents an off-chain account.
/// Fundamental assumption is that only a person (or a group of people) who has access both to the private key of the owner
/// address and to the off-chain account, may be able to generate a valid signature signed by the trusted entity. Once this
/// valid signature is submitted to this contract, it can be verified and used to link or unlink the owner address.
abstract contract OwnershipLink is Ownable2StepMsgSender {
  using EnumerableSet for EnumerableSet.AddressSet;

  // ================================================================
  // |                 Internal variables                            |
  // ================================================================

  mapping(address signer => bool allowed) private s_allowedSigners;
  EnumerableSet.AddressSet private s_linkedOwners;
  mapping(address owner => bytes32 proof) private s_ownerProofs;

  // ================================================================
  // |                         Events                               |
  // ================================================================

  event AllowedSignersUpdatedV1(address[] signers, bool allowed);
  event OwnershipLinkUpdatedV1(address indexed owner, bytes32 indexed proof, bool indexed added);

  // ================================================================
  // |                         Errors                               |
  // ================================================================

  error LinkOwnerRequestExpired(address caller, uint256 currentTime, uint256 expiryTimestamp);
  error UnlinkOwnerRequestExpired(address caller, uint256 currentTime, uint256 expiryTimestamp);
  error OwnershipLinkAlreadyExists(address owner);
  error OwnershipLinkDoesNotExist(address owner);
  error OwnershipLinkProofDoesNotMatch(address owner, bytes32 proof, bytes32 storedProof);
  error InvalidSignature(bytes signature, uint8 recoverErrorId, bytes32 recoverErrorArg);
  error InvalidSValue(bytes signature, bytes32 s);
  error InvalidVValue(bytes signature, uint8 v);
  error InvalidOwnershipLink(address owner, uint256 validityTimestamp, bytes32 proof, bytes signature);

  // ================================================================
  // |                        Modifiers                             |
  // ================================================================

  /// @notice Modifier to check if the transaction sender is on the list of linked owners.
  /// @dev This modifier can be used to restrict access to functions in the derived contract that require
  // the linking to be completed. If the owner address is not linked, the transaction will revert.
  modifier hasOwnerLinked() {
    if (!s_linkedOwners.contains(msg.sender)) {
      revert OwnershipLinkDoesNotExist(msg.sender);
    }
    _;
  }

  // ================================================================
  // |                        Admin Functions                        |
  // ================================================================

  /// @notice Sets the allowed signers for ownership proofs. These signers are considered to be trusted entities.
  /// @param signers The addresses of the signers.
  /// @param allowed The boolean value indicating whether the signer is trusted or not.
  /// @dev Ownership proofs can only be signed by approved group of signers.
  /// When submitting signed proof to this contract, if recovered signature doesn't match any of the signers,
  /// it will be rejected.
  function updateAllowedSigners(address[] calldata signers, bool allowed) public virtual onlyOwner {
    for (uint256 i = 0; i < signers.length; ++i) {
      s_allowedSigners[signers[i]] = allowed;
    }
    emit AllowedSignersUpdatedV1(signers, allowed);
  }

  /// @notice Returns the allowed signer for ownership proofs.
  /// @param signer The address of the signer.
  /// @return The boolean value indicating whether the signer is allowed to sign ownership proofs or not.
  function isAllowedSigner(
    address signer
  ) public view virtual returns (bool) {
    return s_allowedSigners[signer];
  }

  // ================================================================
  // |                Owner linking functions                       |
  // ================================================================

  /// @notice View function to verify if the linkOwner() function can be called successfully.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev This function is used to verify if the ownership proof is valid without actually linking the owner address.
  /// The ownership proof metadata is a combination of the claimed owner address, validity timestamp, and the proof hash.
  /// Request will be rejected if the validity timestamp has expired, owner addres is already linked, if the proof does
  /// not match the one that was originally submitted, or if the signature is not valid (for different reasons).
  /// @dev Verification will use msg.sender as the owner address, which means caller must be the owner of the address,
  /// otherwise the verification will fail with invalid signature error.
  function tryLinkOwner(uint256 validityTimestamp, bytes32 proof, bytes calldata signature) public view virtual {
    if (block.timestamp > validityTimestamp) {
      revert LinkOwnerRequestExpired(msg.sender, block.timestamp, validityTimestamp);
    }

    // This prevents a different owner address from "hijacking" someone else's off-chain account
    if (s_linkedOwners.contains(msg.sender)) {
      revert OwnershipLinkAlreadyExists(msg.sender);
    }

    address signer = _recoverSigner(validityTimestamp, proof, signature);
    if (!s_allowedSigners[signer]) {
      revert InvalidOwnershipLink(msg.sender, validityTimestamp, proof, signature);
    }
  }

  /// @notice Transaction sender submits ownership proof for verification and approval. Upon approval, owner is linked.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev Run the verification process first by calling tryLinkOwner() function. If the verification does not result
  /// in a revert, then the ownership proof is valid and the owner address can be linked.
  function linkOwner(uint256 validityTimestamp, bytes32 proof, bytes calldata signature) public virtual {
    tryLinkOwner(validityTimestamp, proof, signature);

    s_ownerProofs[msg.sender] = proof;
    s_linkedOwners.add(msg.sender);
    emit OwnershipLinkUpdatedV1(msg.sender, proof, true);
  }

  /// @notice View function to verify if the unlinkOwner() function can be called successfully.
  /// @param owner The address of the owner to be unlinked.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev This function is used to verify if the ownership proof is valid without actually unlinking the owner address.
  /// The ownership proof metadata is a combination of the claimed owner address, validity timestamp, and the proof hash.
  /// Request will be rejected if the validity timestamp has expired, owner addres is not linked, if the proof does not
  /// match the one that was originally submitted, or if the signature is not valid (for different reasons).
  /// @dev Important difference between linking and unlinking is that unlinking may be called by any address, as
  /// long as the valid proof is provided. The caller does not have to be the owner of the address being unlinked.
  /// This is done to ensure that unlinking can be done even in cases when access to the private key of the owner
  /// address is lost or compromised, and the owner is not able to submit the unlinking request themselves.
  function tryUnlinkOwner(
    address owner,
    uint256 validityTimestamp,
    bytes32 proof,
    bytes calldata signature
  ) public view virtual {
    if (block.timestamp > validityTimestamp) {
      revert UnlinkOwnerRequestExpired(owner, block.timestamp, validityTimestamp);
    }

    // This prevents unlinking of an owner address that is not even linked to this contract
    if (!s_linkedOwners.contains(owner)) {
      revert OwnershipLinkDoesNotExist(owner);
    }

    // It's very important to check that proof matches the one that was originally submitted from the owner
    // (where msg.sender == owner). For unlinking, we are not enforcing that the caller is the owner, but we
    // are expecting that whoever is calling this function must have access to the original proof signed by the
    // trusted entity. The original proof will be provided only to the ones who has access to the account that
    // was used for linking the owner address.
    bytes32 storedProof = s_ownerProofs[owner];
    if (storedProof != proof) {
      revert OwnershipLinkProofDoesNotMatch(owner, proof, storedProof);
    }

    address signer = _recoverSigner(validityTimestamp, proof, signature);
    if (!s_allowedSigners[signer]) {
      revert InvalidOwnershipLink(owner, validityTimestamp, proof, signature);
    }
  }

  /// @notice Transaction sender submits ownership proof for verification and approval. Upon approval, owner is unlinked.
  /// @param owner The address of the owner to be unlinked.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev Run the verification process first by calling tryUnlinkOwner() function. If the verification does not result
  /// in a revert, then the ownership proof is valid and the owner address can be unlinked.
  function unlinkOwner(
    address owner,
    uint256 validityTimestamp,
    bytes32 proof,
    bytes calldata signature
  ) public virtual {
    tryUnlinkOwner(owner, validityTimestamp, proof, signature);

    s_ownerProofs[owner] = bytes32(0);
    s_linkedOwners.remove(owner);
    emit OwnershipLinkUpdatedV1(owner, proof, false);
  }

  // ================================================================
  // |                      View functions                          |
  // ================================================================

  /// @notice Returns if the owner is linked to this contract.
  /// @param owner The address of the owner.
  /// @return True if the link exists, false otherwise.
  function isOwnerLinked(
    address owner
  ) public view virtual returns (bool) {
    return s_linkedOwners.contains(owner);
  }

  /// @notice Returns total count of linked owners.
  /// @return The total number of linked owners.
  function totalLinkedOwners() public view virtual returns (uint256) {
    return s_linkedOwners.length();
  }

  /// @notice Returns a list of linked owners for the given range.
  /// @param start The starting index of the range.
  /// @param batchSize The size of the batch to return (be vary of using a reasonable value here).
  /// @return A list of linked owners.
  /// @dev The function will return a list of addresses of owners who have submitted ownership proofs in the
  /// order in which they were submitted.
  /// The function will return an empty list if the start index is greater than the total number of owners.
  /// @notice List of owners may change between subsequent calls to this function. It is recommend to call this
  /// function by anchoring a specific block number to ensure the list of owners is immutable between subsequent calls.
  function getLinkedOwners(uint256 start, uint256 batchSize) public view virtual returns (address[] memory) {
    uint256 total = s_linkedOwners.length();
    if (start >= total) {
      return new address[](0);
    }

    uint256 end = (start + batchSize > total) ? total : start + batchSize;
    uint256 length = end - start;
    address[] memory owners = new address[](length);

    for (uint256 i = 0; i < length; ++i) {
      owners[i] = s_linkedOwners.at(start + i);
    }

    return owners;
  }

  // ================================================================
  // |                   Internal functions                         |
  // ================================================================

  /// @notice Returns the signer of the recovered signature or revert.
  /// @param validityTimestamp The validity timestamp of the ownership proof.
  /// @param proof The ownership proof.
  /// @param signature The signature of the ownership proof metadata.
  /// @return The signer of the recovered signature.
  /// @dev The function tries to re-generate the message digest based on the provided parameters and by following
  /// EIP-191. The it will try to recover the signer address. The function will revert if the signature is invalid.
  function _recoverSigner(
    uint256 validityTimestamp,
    bytes32 proof,
    bytes memory signature
  ) internal view returns (address) {
    // Follow EIP-191 for recoverable signatures
    bytes32 prefixedMessageHash = MessageHashUtils.toEthSignedMessageHash(
      keccak256(abi.encodePacked(msg.sender, block.chainid, address(this), validityTimestamp, proof))
    );

    (address signer, ECDSA.RecoverError err, bytes32 errArg) = ECDSA.tryRecover(prefixedMessageHash, signature);
    if (err != ECDSA.RecoverError.NoError) {
      revert InvalidSignature(signature, uint8(err), errArg);
    }

    return signer;
  }
}
