// SPDX-License-Identifier: BUSL 1.1
pragma solidity 0.8.26;

import {ITypeAndVersion} from "../../../shared/interfaces/ITypeAndVersion.sol";

import {Ownable2StepMsgSender} from "../../../shared/access/Ownable2StepMsgSender.sol";

import {Strings} from "@openzeppelin/contracts@5.1.0/utils/Strings.sol";
import {ECDSA} from "@openzeppelin/contracts@5.1.0/utils/cryptography/ECDSA.sol";
import {MessageHashUtils} from "@openzeppelin/contracts@5.1.0/utils/cryptography/MessageHashUtils.sol";
import {EnumerableMap} from "@openzeppelin/contracts@5.1.0/utils/structs/EnumerableMap.sol";
import {EnumerableSet} from "@openzeppelin/contracts@5.1.0/utils/structs/EnumerableSet.sol";

contract WorkflowRegistry is Ownable2StepMsgSender, ITypeAndVersion {
  using EnumerableSet for EnumerableSet.Bytes32Set;
  using EnumerableSet for EnumerableSet.AddressSet;
  using EnumerableMap for EnumerableMap.AddressToBytes32Map;

  string public constant override typeAndVersion = "WorkflowRegistry 2.0.0-dev";
  uint8 private constant MAX_WORKFLOW_NAME_LENGTH = 64;
  uint8 private constant MAX_WORKFLOW_TAG_LENGTH = 32;
  uint8 private constant MAX_URL_LENGTH = 200;
  uint8 private constant MAX_PAGINATION_LIMIT = 100;
  uint16 private constant MAX_ATTRIBUTES_LENGTH = 512; // 0.5 kilobyte

  /// @dev The set of allowed signers for ownership proofs. These signers are considered to be trusted entities.
  /// If the ownership proof is not signed by one of the allowed signers, signature will be rejected.
  mapping(address signer => bool allowed) private s_allowedSigners;
  /// @dev The set of linked owners. These are the addresses that have successfully linked their ownership proofs.
  /// Ownership proofs are signed messages generated by a trusted entity, with each proof being unique for each owner
  /// address. The owner address is embedded into the proof itself together with other relevant metadata that uniquely
  /// represents an off-chain account.
  /// Fundamental assumption is that only a person (or a group of people) who has access both to the private key of the owner
  /// address and to the off-chain account, may be able to generate a valid signature signed by the trusted entity. Once this
  /// valid signature is submitted to this contract, it can be verified and used to link or unlink the owner address.
  EnumerableMap.AddressToBytes32Map private s_linkedOwners;
  /// @dev This is a mapping of ownership proofs indicating whether the proof has been previously used or not. This is used
  /// to prevent someone from re-using the same proof for linking more than once, and ensures that each proof is unique per
  /// single linking request, not matter if it originates from the same owner address or not. This allows us to verifiably
  /// enforce an invariant on proofs.
  mapping(bytes32 proof => bool used) private s_usedProofs;

  /// @dev workflowRid (reference ID) is a hash of (owner ∥ name ∥ label). It functions as the primary index for the workflow storage.
  mapping(bytes32 workflowRid => WorkflowMetadata workflowMetadata) private s_workflows;
  /// @dev workflowKey is a hash of (owner ∥ name ) and maps to a set of Rids. It is used for filtering workflows based on just
  /// the name, as there may be multiple workflows with the same name under a different tag.
  mapping(bytes32 workflowKey => EnumerableSet.Bytes32Set) private s_workflowKeyToRids;
  /// @dev workflowId ⇒ workflowRid. This mapping lets us enforce global uniqueness of workflowId while also allows us to lookup
  /// workflows through the workflowId.
  mapping(bytes32 workflowId => bytes32 workflowRid) private s_idToRid;

  // Secondary indices for iteration / queries
  mapping(address owner => EnumerableSet.Bytes32Set workflowRids) private s_activeOwnerWorkflowRids; // owner -> workflowRid set
  mapping(bytes32 donLabel => EnumerableSet.Bytes32Set workflowRids) private s_activeDONWorkflowRids; // donLabel -> workflowRid set

  /// @dev Every workflow ever registered under `donLabel`. Pruned only on delete.
  mapping(bytes32 donLabel => EnumerableSet.Bytes32Set workflowRids) private s_allDONRids;
  /// @dev Every workflow ever registered for an owner. Pruned only on delete.
  mapping(address owner => EnumerableSet.Bytes32Set workflowRids) private s_allOwnerRids;
  mapping(bytes32 workflowKey => EnumerableSet.Bytes32Set activeRids) private s_activeRidsByWorkflowKey; // workflowKey → active Rids
  // Fast counters for limits enforcement
  mapping(address owner => mapping(bytes32 donLabel => uint32 workflowCount)) private s_userDONCount; // owner -> (donLabel -> #workflows)

  // ================================================================
  // |                         Events                               |
  // ================================================================

  event AllowedSignersUpdated(address[] signers, bool allowed);
  event OwnershipLinkUpdated(address indexed owner, bytes32 indexed proof, bool indexed added);
  event DONLimitSet(bytes32 indexed donLabel, uint32 limit);
  event UserDONLimitSet(address indexed user, bytes32 indexed donLabel, uint32 limit);
  event UserDONLimitUnset(address indexed user, bytes32 indexed donLabel);
  event WorkflowRegistered(
    bytes32 indexed workflowId, address indexed owner, bytes32 donLabel, WorkflowStatus status, string workflowName
  );
  event WorkflowUpdated(
    bytes32 indexed oldWorkflowId,
    bytes32 indexed newWorkflowId,
    address indexed owner,
    bytes32 donLabel,
    string workflowName
  );
  event WorkflowPaused(
    bytes32 indexed workflowId, address indexed owner, bytes32 indexed donLabel, string workflowName
  );
  event WorkflowActivated(
    bytes32 indexed workflowId, address indexed owner, bytes32 indexed donLabel, string workflowName
  );
  event WorkflowDeleted(
    bytes32 indexed workflowId, address indexed owner, bytes32 indexed donLabel, string workflowName
  );

  // ================================================================
  // |                         Errors                               |
  // ================================================================

  error ZeroAddressNotAllowed();
  error LinkOwnerRequestExpired(address caller, uint256 currentTime, uint256 expiryTimestamp);
  error UnlinkOwnerRequestExpired(address caller, uint256 currentTime, uint256 expiryTimestamp);
  error OwnershipLinkAlreadyExists(address owner);
  error OwnershipLinkDoesNotExist(address owner);
  error InvalidSignature(bytes signature, uint8 recoverErrorId, bytes32 recoverErrorArg);
  error InvalidOwnershipLink(address owner, uint256 validityTimestamp, bytes32 proof, bytes signature);
  error OwnershipProofAlreadyUsed(address caller, bytes32 proof);
  error CannotUnlinkWithActiveWorkflows();
  error CallerIsNotWorkflowOwner(address caller);
  error MaxWorkflowsPerDONExceeded(bytes32 donLabel);
  error MaxWorkflowsPerUserDONExceeded(address owner, bytes32 donLabel);
  error UserDONOverrideExceedsDONLimit();
  error URLTooLong(uint256 provided, uint8 maxAllowed);
  error WorkflowAlreadyInDesiredStatus();
  error WorkflowDoesNotExist();
  error WorkflowIDAlreadyExists(bytes32 workflowId);
  error WorkflowNameRequired();
  error WorkflowNameTooLong(uint256 provided, uint8 maxAllowed);
  error WorkflowTagRequired();
  error WorkflowTagTooLong(uint256 provided, uint8 maxAllowed);
  error AttributesTooLong(uint256 provided, uint256 maxAllowed);
  error EmptyUpdateBatch();

  // ================================================================
  // |                         Enums                                |
  // ================================================================

  enum WorkflowStatus {
    ACTIVE,
    PAUSED
  }

  enum PreUnlinkAction {
    NONE, //              No action prior to unlinking.
    REMOVE_WORKFLOWS, //  Remove all workflows owned by the owner prior to unlinking.
    PAUSE_WORKFLOWS //    Pause all workflows owned by the owner prior to unlinking.

  }

  enum LinkingRequestType {
    LINK_OWNER, //       Request to link an owner address.
    UNLINK_OWNER //       Request to unlink an owner address.

  }

  struct WorkflowMetadata {
    bytes32 workflowId; //       Unique identifier from hash(owner, workflow name, wasm binary, cfg).
    address owner; // ─────────╮ Workflow owner.
    uint64 createdAt; //       │ block.timestamp when the workflow was first registered.
    WorkflowStatus status; // ─╯ Current status of the workflow (active, paused).
    bytes32 donLabel; //         Label for the DON (32 chars limit) in bytes32.
    string workflowName; //      Human readable string (64 chars limit).
    string binaryUrl; //         URL to the wasm binary (200 chars limit).
    string configUrl; //         URL to the config (200 chars limit).
    string tag; //               Unique per (owner, workflowName) human readable identifier (32 chars limit)
    bytes attributes; //         Arbitrary bytes for additional workflow details.
  }

  // ================================================================
  // |                        Limits Config                         |
  // ================================================================
  // Struct to distinguish between unset and explicitly set zero values
  struct ConfigValue {
    uint32 value;
    bool enabled;
  }

  /// @dev Configuration struct for maximum active workflows. Paused workflows are ignored.
  struct Config {
    mapping(bytes32 donLabel => ConfigValue limitValue) donLimit;
    mapping(address user => mapping(bytes32 donLabel => ConfigValue limitValue)) userDONOverride;
  }

  Config private s_cfg;

  /// @notice Sets or clears a DON-wide limit for the maximum number of
  ///         ACTIVE workflows.
  /// @dev    Only callable by the contract owner.
  ///         When `enabled` is true, a limit is added for the DON label.
  ///         When `enabled` is false, the existing limit is removed.
  ///         When both adding and removing, an event record is created for the event, and the event itself
  ///         is emited in the internal helper.
  /// @param  donLabel  Bytes32-padded DON label used as the mapping key.
  /// @param  limit     New cap to apply when `enabled` is true.
  /// @param  enabled   Flag indicating whether to store (`true`) or delete (`false`)
  ///                   the override entry.
  function setDONLimit(bytes32 donLabel, uint32 limit, bool enabled) external onlyOwner {
    if (enabled) {
      s_cfg.donLimit[donLabel] = ConfigValue(limit, true);
      _pushDONCapacitySet(donLabel, limit);
    } else {
      delete s_cfg.donLimit[donLabel];
      _pushDONCapacitySet(donLabel, 0);
    }
  }

  /// @notice Sets or removes a per-user, per-DON limit for ACTIVE workflows.
  /// @dev    Only the contract owner may call this.
  ///         - When `enabled` is true, stores the override and emits `UserDONLimitSet(user, donLabel, limit)`.
  ///         - When `enabled` is false, deletes any override and emits `UserDONLimitUnset(user, donLabel)`.
  ///         The per-user override `limit` must not exceed the global DON limit, otherwise it reverts.
  ///         When per-user overrides are added or removed, no event record is added because this does not affect the
  ///         actual capacity of the DON as it is already constrained by the DON capacity.
  /// @param  user      The address whose per-DON override is being modified.
  /// @param  donLabel  The 32-byte identifier of the DON whose limit is overridden.
  /// @param  limit     The new cap to enforce when the override is enabled.
  /// @param  enabled   True to store the override, false to remove it.
  function setUserDONOverride(address user, bytes32 donLabel, uint32 limit, bool enabled) external onlyOwner {
    if (enabled) {
      if (limit > s_cfg.donLimit[donLabel].value) {
        revert UserDONOverrideExceedsDONLimit();
      }

      s_cfg.userDONOverride[user][donLabel] = ConfigValue(limit, true);
      emit UserDONLimitSet(user, donLabel, limit);
    } else {
      delete s_cfg.userDONOverride[user][donLabel];
      emit UserDONLimitUnset(user, donLabel);
    }
  }

  /// @notice Gets the configured maximum number of workflows for a given DON label.
  /// @dev DON labels must first be configured in the Config.donLimit before workflows can be created against them.
  /// @param donLabel The identifier of the DON whose workflow cap is being queried.
  /// @return maxWorkflows The maximum number of workflows allowed for the specified DON, or zero if the DON
  ///                      is not allowlisted or no limit has been explicitly set.
  function getMaxWorkflowsPerDON(
    bytes32 donLabel
  ) public view returns (uint32) {
    return s_cfg.donLimit[donLabel].value;
  }

  /// @notice Returns the active-workflow cap that applies to a given DON and user.
  /// @dev    If a DON-specific user override is present and enabled, that override value
  ///         is returned; otherwise, the DON’s default limit is used.
  /// @param  user     Address of the user whose override limit is being queried.
  /// @param  donLabel Bytes32-padded identifier of the DON.
  /// @return maxActive Maximum number of ACTIVE workflows allowed for the user on that DON.
  function getMaxWorkflowsPerUserDON(address user, bytes32 donLabel) public view returns (uint32) {
    ConfigValue memory cfgVal = s_cfg.userDONOverride[user][donLabel];
    if (cfgVal.enabled) {
      return cfgVal.value;
    }
    return s_cfg.donLimit[donLabel].value;
  }

  // ================================================================
  // |                         DON registry                         |
  // ================================================================
  /// @notice  Stores the pointer to the DON Registry this Workflow Registry uses.
  /// @dev     `registry` is the contract address; `chainSelector` identifies the
  ///          chain where the registry lives (Chainlink CCIP selector style).
  struct DONRegistryConfig {
    address registry;
    uint256 chainSelector;
  }

  /// @dev Stores the current DON Registry reference used by this contract.
  DONRegistryConfig private s_donRegistry;

  /// @notice Emitted whenever the registry reference is changed.
  /// @param oldAddr       Previous registry address (zero if first set).
  /// @param newAddr       New registry address being stored.
  /// @param chainSelector CCIP-style chain selector where the registry lives.
  event DONRegistryUpdated(address indexed oldAddr, address indexed newAddr, uint256 indexed chainSelector);

  /// @notice Sets or replaces the DON Registry that this Workflow Registry points to.
  /// @dev    Owner-only.  Overwrites the previous entry and emits
  ///         {DONRegistryUpdated}.
  /// @param  registry       Address of the DON Registry contract.
  /// @param  chainSelector  CCIP chain selector for the registry’s chain.
  function setDONRegistry(address registry, uint256 chainSelector) external onlyOwner {
    address old = s_donRegistry.registry;
    s_donRegistry = DONRegistryConfig({registry: registry, chainSelector: chainSelector});
    emit DONRegistryUpdated(old, registry, chainSelector);
  }

  // ================================================================
  // |               Linking Admin Functions                        |
  // ================================================================

  /// @notice Sets the allowed signers for ownership proofs. These signers are considered to be trusted entities.
  /// @param signers The addresses of the signers.
  /// @param allowed The boolean value indicating whether the signer is trusted or not.
  /// @dev Ownership proofs can only be signed by approved group of signers.
  /// When submitting signed proof to this contract, if recovered signature doesn't match any of the signers,
  /// it will be rejected.
  function updateAllowedSigners(address[] calldata signers, bool allowed) external onlyOwner {
    for (uint256 i = 0; i < signers.length; ++i) {
      if (signers[i] == address(0)) {
        revert ZeroAddressNotAllowed();
      }
      s_allowedSigners[signers[i]] = allowed;
    }
    emit AllowedSignersUpdated(signers, allowed);
  }

  /// @notice Returns the allowed signer for ownership proofs.
  /// @param signer The address of the signer.
  /// @return The boolean value indicating whether the signer is allowed to sign ownership proofs or not.
  function isAllowedSigner(
    address signer
  ) external view returns (bool) {
    return s_allowedSigners[signer];
  }

  // ================================================================
  // |                Owner linking functions                       |
  // ================================================================
  /// @notice View function to verify if the linkOwner() function can be called successfully.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev This function is used to verify if the ownership proof is valid without actually linking the owner address.
  /// The ownership proof metadata is a combination of the claimed owner address, validity timestamp, and the proof hash.
  /// Request will be rejected if the validity timestamp has expired, owner addres is already linked, if the proof does
  /// not match the one that was originally submitted, or if the signature is not valid (for different reasons).
  /// @dev Verification will use msg.sender as the owner address, which means caller must be the owner of the address,
  /// otherwise the verification will fail with invalid signature error.
  function canLinkOwner(uint256 validityTimestamp, bytes32 proof, bytes calldata signature) public view {
    if (block.timestamp > validityTimestamp) {
      revert LinkOwnerRequestExpired(msg.sender, block.timestamp, validityTimestamp);
    }

    // Workflow owner address may only be linked once
    if (s_linkedOwners.contains(msg.sender)) {
      revert OwnershipLinkAlreadyExists(msg.sender);
    }

    // Ownership proof must be unique and must not be used for linking more than once
    if (s_usedProofs[proof]) {
      revert OwnershipProofAlreadyUsed(msg.sender, proof);
    }

    address signer =
      _recoverSigner(uint8(LinkingRequestType.LINK_OWNER), msg.sender, validityTimestamp, proof, signature);
    if (!s_allowedSigners[signer]) {
      revert InvalidOwnershipLink(msg.sender, validityTimestamp, proof, signature);
    }
  }

  /// @notice Transaction sender submits ownership proof for verification and approval. Upon approval, owner is linked.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev Run the verification process first by calling canLinkOwner() function. If the verification does not result
  /// in a revert, then the ownership proof is valid and the owner address can be linked.
  function linkOwner(uint256 validityTimestamp, bytes32 proof, bytes calldata signature) external {
    canLinkOwner(validityTimestamp, proof, signature);

    s_linkedOwners.set(msg.sender, proof);
    s_usedProofs[proof] = true;
    emit OwnershipLinkUpdated(msg.sender, proof, true);
  }

  /// @notice View function to verify if the unlinkOwner() function can be called successfully.
  /// @param owner The address of the owner to be unlinked.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param signature The signature of the ownership proof metadata.
  /// preUnlinkAction Determines what to do with existing workflows owned by the owner before unlinking.
  /// @dev If preUnlinkAction is NONE, the function will check if there are any active workflows registered to the
  /// owner, and if so, the transaction will revert. If preUnlinkAction is not NONE, then all workflows owned by this
  /// owner's address will be removed or paused before unlinking is completed.
  /// @dev This function is used to verify if the ownership proof is valid without actually unlinking the owner address.
  /// The ownership proof metadata is a combination of the claimed owner address, validity timestamp, and the proof hash.
  /// Request will be rejected if the validity timestamp has expired, owner addres is not linked, if the proof does not
  /// match the one that was originally submitted, or if the signature is not valid (for different reasons).
  /// @dev It is essential to ensure that the unlinking process does not leave any active workflows running because
  /// they can't be managed on the registry by anyone else aside from a valid owner. Without this, the workflows
  /// would be stuck since they can't be managed or removed by anyone.
  /// @dev Important difference between linking and unlinking is that unlinking may be called by any address, as
  /// long as the valid proof is provided. The caller does not have to be the owner of the address being unlinked.
  /// This is done to ensure that unlinking can be done even in cases when access to the private key of the owner
  /// address is lost or compromised, and the owner is not able to submit the unlinking request themselves.
  function canUnlinkOwner(
    address owner,
    uint256 validityTimestamp,
    bytes calldata signature,
    PreUnlinkAction action
  ) public view {
    if (action == PreUnlinkAction.NONE) {
      _requireNoActiveWorkflows(owner);
    }

    _validateOwnershipLinks(owner, validityTimestamp, signature);
  }

  /// @notice Transaction sender submits ownership proof for verification and approval. Upon approval, owner is unlinked.
  /// @param owner The address of the owner to be unlinked.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param signature The signature of the ownership proof metadata.
  /// preUnlinkAction Determines what to do with existing workflows owned by the owner before unlinking.
  /// @dev If preUnlinkAction is NONE, the function will check if there are any active workflows registered to the
  /// owner, and if so, the transaction will revert. If preUnlinkAction is not NONE, then all workflows owned by this
  /// owner's address will be removed or paused before unlinking is completed.
  /// @dev Run the verification process first by calling canUnlinkOwner() function. If the verification does not result
  /// in a revert, then the ownership proof is valid and the owner address can be unlinked.
  function unlinkOwner(
    address owner,
    uint256 validityTimestamp,
    bytes calldata signature,
    PreUnlinkAction action
  ) external {
    if (action == PreUnlinkAction.NONE) {
      _requireNoActiveWorkflows(owner);
    }

    _validateOwnershipLinks(owner, validityTimestamp, signature);
    if (action != PreUnlinkAction.NONE) {
      _handlePreUnlinkAction(owner, action);
    }

    bytes32 storedProof = s_linkedOwners.get(owner);
    s_linkedOwners.remove(owner);
    emit OwnershipLinkUpdated(owner, storedProof, false);
  }

  /// @notice Returns if the owner is linked to this contract.
  /// @param owner The address of the owner.
  /// @return True if the link exists, false otherwise.
  function isOwnerLinked(
    address owner
  ) external view returns (bool) {
    return s_linkedOwners.contains(owner);
  }

  /// @notice Returns total count of linked owners.
  /// @return The total number of linked owners.
  function totalLinkedOwners() external view returns (uint256) {
    return s_linkedOwners.length();
  }

  /// @notice Retrieves a paginated list of addresses that have linked ownership proofs.
  /// @param start Zero-based index of the first owner to include in the result.
  /// @param limit Maximum number of owners to return (clamped by a sensible internal cap).
  /// @return owners An array of owner addresses in the order they were linked.
  /// @dev    - If `start` ≥ total linked owners, returns an empty array.
  ///         - The list can change between calls; for an immutable snapshot, query at a specific block.
  function getLinkedOwners(uint256 start, uint256 limit) external view returns (address[] memory owners) {
    uint256 total = s_linkedOwners.length();
    (uint256 offset, uint256 count) = _getPageBounds(total, start, limit);

    owners = new address[](count);
    for (uint256 i = 0; i < count; ++i) {
      (owners[i],) = s_linkedOwners.at(offset + i);
    }

    return owners;
  }

  /// @notice Returns the signer of the recovered signature or revert.
  /// @param requestType The type of the request (LINK_OWNER = 0 or UNLINK_OWNER = 1).
  /// @param owner The address of the owner.
  /// @param validityTimestamp The validity timestamp of the ownership proof.
  /// @param proof The ownership proof.
  /// @param signature The signature of the ownership proof metadata.
  /// @return The signer of the recovered signature.
  /// @dev The function tries to re-generate the message digest based on the provided parameters and by following
  /// EIP-191. The it will try to recover the signer address. The function will revert if the signature is invalid.
  function _recoverSigner(
    uint8 requestType,
    address owner,
    uint256 validityTimestamp,
    bytes32 proof,
    bytes calldata signature
  ) internal view returns (address) {
    // Follow EIP-191 for recoverable signatures
    bytes32 prefixedMessageHash = MessageHashUtils.toEthSignedMessageHash(
      keccak256(abi.encode(requestType, owner, block.chainid, address(this), typeAndVersion, validityTimestamp, proof))
    );

    (address signer, ECDSA.RecoverError err, bytes32 errArg) = ECDSA.tryRecover(prefixedMessageHash, signature);
    if (err != ECDSA.RecoverError.NoError) {
      revert InvalidSignature(signature, uint8(err), errArg);
    }

    return signer;
  }

  /// @dev Reverts when `owner` still has ACTIVE workflows.
  function _requireNoActiveWorkflows(
    address owner
  ) private view {
    if (s_activeOwnerWorkflowRids[owner].length() != 0) {
      revert CannotUnlinkWithActiveWorkflows();
    }
  }

  /// @dev    Executes the pre-unlink action.
  /// @param  owner     The owner being unlinked.
  /// @param  action    NONE / PAUSE_WORKFLOWS / REMOVE_WORKFLOWS (expects action ≠ NONE)
  function _handlePreUnlinkAction(address owner, PreUnlinkAction action) internal {
    EnumerableSet.Bytes32Set storage active = s_activeOwnerWorkflowRids[owner];
    // ------------- PAUSE or DELETE -------------
    // Iterate from the back since EnumerableSet.remove() swaps-and-pops.
    while (active.length() > 0) {
      bytes32 rid = active.at(active.length() - 1);
      WorkflowMetadata storage rec = _getWorkflowFromStorage(owner, rid);
      if (action == PreUnlinkAction.PAUSE_WORKFLOWS) {
        _applyPause(rid, rec);
      } else {
        _applyDelete(rid, rec);
      }
    }
  }

  /// @dev Reverts unless `owner` is in the linked-owners set.
  /// @param owner Address to verify (usually msg.sender).
  function _requireOwnerLinked(
    address owner
  ) internal view {
    if (!s_linkedOwners.contains(owner)) {
      revert OwnershipLinkDoesNotExist(owner);
    }
  }

  function _validateOwnershipLinks(address owner, uint256 validityTimestamp, bytes calldata signature) internal view {
    if (block.timestamp > validityTimestamp) {
      revert UnlinkOwnerRequestExpired(owner, block.timestamp, validityTimestamp);
    }

    _requireOwnerLinked(owner);

    // The expectation is that the signature must contain the same proof that was originally used for the linking
    bytes32 storedProof = s_linkedOwners.get(owner);

    // Request type prevents replay attacks, since the same proof can be used for both linking and unlinking
    address signer =
      _recoverSigner(uint8(LinkingRequestType.UNLINK_OWNER), owner, validityTimestamp, storedProof, signature);
    if (!s_allowedSigners[signer]) {
      revert InvalidOwnershipLink(owner, validityTimestamp, storedProof, signature);
    }
  }

  // ================================================================
  // |                   Capacity Changing Events                   |
  // ================================================================
  enum EventType {
    DONCapacitySet,
    WorkflowAdded,
    WorkflowRemoved
  }

  struct EventRecord {
    EventType eventType;
    uint32 timestamp;
    bytes payload; // ABI‑encoded event data
  }

  // Storage of all capacity and workflow life‑cycle events
  EventRecord[] private s_events;

  /// @notice Emit and save an event recording that the global capacity for a DON label has been set.
  /// @dev    Called whenever the `s_cfg.donLimit[donLabel]` value is updated in configuration.
  ///         Does **not** fire for per-user overrides, since those limits are always constrained
  ///         by the global DON limit and are not considered standalone capacity changes.
  /// @param  donLabel The `bytes32` identifier of the DON whose capacity was updated.
  /// @param  capacity The new maximum number of workflows allowed for this DON.
  function _pushDONCapacitySet(bytes32 donLabel, uint32 capacity) internal {
    s_events.push(
      EventRecord({
        eventType: EventType.DONCapacitySet,
        timestamp: uint32(block.timestamp),
        payload: abi.encode(donLabel, capacity)
      })
    );

    emit DONLimitSet(donLabel, capacity);
  }

  /// @notice Record that a workflow has been activated (added to active sets).
  /// @dev    Performs two actions in order:
  ///           1. Appends an internal `WorkflowAdded` entry to `s_events` for off-chain history.
  ///           2. Emits the public `WorkflowActivated` event so on-chain listeners are notified.
  /// @param  workflowId   The unique `bytes32` identifier of the workflow.
  /// @param  owner        The address that owns this workflow.
  /// @param  donLabel     The DON label under which the workflow is registered.
  /// @param  workflowName The human-readable name of the workflow.
  function _pushWorkflowAdded(
    bytes32 workflowId,
    address owner,
    bytes32 donLabel,
    string storage workflowName
  ) internal {
    s_events.push(
      EventRecord({
        eventType: EventType.WorkflowAdded,
        timestamp: uint32(block.timestamp),
        payload: abi.encode(workflowId, owner, donLabel, workflowName)
      })
    );

    emit WorkflowActivated(workflowId, owner, donLabel, workflowName);
  }

  /// @notice Record that a workflow has been paused (removed from active sets).
  /// @dev    Performs two actions:
  ///           1. Appends an internal `WorkflowRemoved` entry to `s_events` for off-chain processing.
  ///           2. Emits the public `WorkflowPaused` event so on-chain listeners are notified.
  /// @param  workflowId   The unique `bytes32` ID of the workflow being paused.
  /// @param  owner        The address that owns this workflow.
  /// @param  donLabel     The DON label under which the workflow was registered.
  /// @param  workflowName The human-readable name of the workflow.
  function _pushWorkflowRemoved(
    bytes32 workflowId,
    address owner,
    bytes32 donLabel,
    string storage workflowName
  ) internal {
    s_events.push(
      EventRecord({
        eventType: EventType.WorkflowRemoved,
        timestamp: uint32(block.timestamp),
        payload: abi.encode(workflowId, owner, donLabel, workflowName)
      })
    );

    emit WorkflowPaused(workflowId, owner, donLabel, workflowName);
  }

  /// @notice Returns a page of events along with the total event count.
  /// @param start Zero-based index of the first event to include in the page.
  /// @param limit  Maximum number of events to return in this page.
  /// @return list  Array of events in the requested window.
  function getEvents(uint256 start, uint256 limit) external view returns (EventRecord[] memory list) {
    uint256 total = s_events.length;
    (uint256 offset, uint256 count) = _getPageBounds(total, start, limit);

    list = new EventRecord[](count);
    for (uint256 i = 0; i < count; i++) {
      list[i] = s_events[offset + i];
    }

    return list;
  }

  // ================================================================
  // |                       Workflow Management                    |
  // ================================================================
  /// Storage invariant:
  ///   - `s_workflows` RID is the primary key on the workflow storage.
  /// .   It is comprised of a hash of the (workflowName, workflowOwner, workflowTag)
  ///
  ///   - Every **active** workflow adds to:
  ///         • `s_activeDONWorkflowRids[don]`
  ///         • `s_activeOwnerWorkflowRids[owner];
  ///         • `s_userDONCount[owner][don]`
  ///         • `s_activeRidsByWorkflowKey[key]`
  ///   - Similarly, every deactivation removes from the above indices.
  ///   - Status transitions must update **all four** structures.
  ///
  /// @notice Upserts a new workflow based on workflowName + owner + tag. If triplet already exist
  /// as a record, then we will update that existing workflow. Otherwise, a new one with the new
  /// tag is created.
  /// Status and donLabel cannot be updated via upsert. They must use their own separate functions
  /// for any changes to these workflow fields.
  /// @param workflowName  Human‑readable name (≤64 chars)
  /// @param workflowId    Deterministic hash computed off‑chain (must be unique)
  /// @param donLabel      Label of the DON (32 chars limit)
  /// @param status        Initial status (ACTIVE / PAUSED)
  /// @param binaryUrl     URL of the wasm binary (required)
  /// @param configUrl     URL of the config (optional)
  /// @param attributes    Arbitrary bytes for additional workflow details (optional)
  /// @param keepAlive     Boolean flag that determines whether existing workflows with the same
  /// workflowName, workflowOwner combination should be paused or kept active.
  function upsertWorkflow(
    string calldata workflowName,
    string calldata tag,
    bytes32 workflowId,
    WorkflowStatus status,
    bytes32 donLabel,
    string calldata binaryUrl,
    string calldata configUrl,
    bytes calldata attributes,
    bool keepAlive
  ) external {
    bytes32 rid = _workflowRid(msg.sender, workflowName, tag);
    if (s_workflows[rid].owner == address(0)) {
      _createWorkflow(rid, workflowName, tag, workflowId, status, donLabel, binaryUrl, configUrl, attributes, keepAlive);
    } else {
      _updateWorkflow(rid, workflowName, workflowId, binaryUrl, configUrl, attributes);
    }
  }

  /// @dev Creates a new workflow record under the caller’s address.
  ///  Phases:
  ///   0. Validation          – basic parameter and length checks.
  ///   1. Limit checks        – enforced only when `status` is ACTIVE.
  ///   2. House-keeping       – optionally pause older ACTIVE versions
  ///                            sharing the same (owner, name) key.
  ///   3. Write primary record.
  ///   4. Update indices & counters.
  ///   5. Emit WorkflowRegistered.
  /// @param rid         Primary-key RID = keccak(owner, name, tag).
  /// @param workflowName Human-readable name (≤64 chars).
  /// @param tag         Workflow tag (≤32 chars) — part of the primary key.
  /// @param workflowId  Deterministic ID (must be globally unique).
  /// @param status      Initial status (ACTIVE or PAUSED).
  /// @param donLabel    Bytes32-padded DON label this workflow runs on.
  /// @param binaryUrl   Optional URL of the Wasm binary (≤200 chars).
  /// @param configUrl   Optional URL of the config file  (≤200 chars).
  /// @param attributes  Arbitrary extra data blob.
  /// @param keepAlive   When false, pause any existing ACTIVE workflow
  ///                    with the same (owner, name) but different tag.
  function _createWorkflow(
    bytes32 rid,
    string calldata workflowName,
    string calldata tag,
    bytes32 workflowId,
    WorkflowStatus status,
    bytes32 donLabel,
    string calldata binaryUrl,
    string calldata configUrl,
    bytes calldata attributes,
    bool keepAlive
  ) internal {
    /* ───────────────────────── 0. VALIDATION ─────────────────────────── */
    _requireOwnerLinked(msg.sender);
    _validateWorkflowName(bytes(workflowName).length);
    _validateWorkflowTag(bytes(tag).length);
    _validateWorkflowID(workflowId);
    _validateWorkflowURLs(bytes(binaryUrl).length, bytes(configUrl).length);
    _validateAttributesLength(attributes.length);

    bytes32 wKey = _workflowKey(msg.sender, workflowName);

    /* ───────────────────────── 1. LIMIT CHECKS ───────────────────────── */
    if (status == WorkflowStatus.ACTIVE) {
      _enforceLimits(msg.sender, donLabel);
    }

    /* ───────────────────────── 2. HOUSEKEEPING ───────────────────────── */
    if (!keepAlive) {
      _pauseAllActiveWorkflowsByWorkflowKey(wKey);
    }

    /* ───────────────────────── 3. WRITE PRIMARY RECORD ───────────────── */
    s_workflows[rid] = WorkflowMetadata({
      workflowId: workflowId,
      owner: msg.sender,
      createdAt: uint64(block.timestamp),
      status: status,
      workflowName: workflowName,
      donLabel: donLabel,
      binaryUrl: binaryUrl,
      configUrl: configUrl,
      tag: tag,
      attributes: attributes
    });

    /* ───────────────────────── 4. UPDATE INDICES ─────────────────────── */
    s_workflowKeyToRids[wKey].add(rid);
    s_idToRid[workflowId] = rid;
    s_allDONRids[donLabel].add(rid);
    s_allOwnerRids[msg.sender].add(rid);

    if (status == WorkflowStatus.ACTIVE) {
      s_activeDONWorkflowRids[donLabel].add(rid);
      s_activeOwnerWorkflowRids[msg.sender].add(rid);
      s_userDONCount[msg.sender][donLabel] += 1;
      s_activeRidsByWorkflowKey[wKey].add(rid);
    }

    /* ───────────────────────── 5. EVENT LOG ──────────────────────────── */
    emit WorkflowRegistered(workflowId, msg.sender, donLabel, status, workflowName);
  }

  /// @dev Update a workflow’s mutable metadata while leaving its DON label and status untouched.
  /// Maintains all registry invariants:
  ///  1. Removes the old `workflowId` from `s_idToRid`, inserts the new one
  ///  2. Emits `WorkflowUpdated` with the previous ID (`oldWorkflowId`)
  ///      and the new ID so that off-chain indexers can track replacements.
  ///
  /// Requirements:
  ///  • `msg.sender` must be a linked owner (`_requireOwnerLinked`).
  ///  • `newWorkflowId` must be non-zero and globally unused.
  ///
  /// @param rid             Primary storage key (hash of owner ∥ name ∥ tag).
  /// @param workflowName    Human-readable name; only needed to recompute the
  ///                        workflow-key (`wKey`) pointer.
  /// @param newWorkflowId   Fresh, globally-unique workflow identifier.
  /// @param newBinaryUrl    Optional new WASM binary URL (≤ 200 chars).
  /// @param newConfigUrl    Optional new config URL (≤ 200 chars).
  /// @param newAttributes   Optional opaque attribute blob.
  function _updateWorkflow(
    bytes32 rid,
    string calldata workflowName,
    bytes32 newWorkflowId,
    string calldata newBinaryUrl,
    string calldata newConfigUrl,
    bytes calldata newAttributes
  ) internal {
    _requireOwnerLinked(msg.sender);
    _validateWorkflowID(newWorkflowId);
    _validateWorkflowURLs(bytes(newBinaryUrl).length, bytes(newConfigUrl).length);
    _validateAttributesLength(newAttributes.length);

    WorkflowMetadata storage rec = _getWorkflowFromStorage(msg.sender, rid);

    /* ─────── 2. PRIMARY-KEY REMAP ─────── */
    delete s_idToRid[rec.workflowId];
    s_idToRid[newWorkflowId] = rid;

    /* ─────── 3. FIELD PATCHES ─────── */
    bytes32 oldWorkflowId = rec.workflowId;
    rec.workflowId = newWorkflowId;
    if (!Strings.equal(rec.binaryUrl, newBinaryUrl)) rec.binaryUrl = newBinaryUrl;
    if (!Strings.equal(rec.configUrl, newConfigUrl)) rec.configUrl = newConfigUrl;
    rec.attributes = newAttributes;

    /* ─────── 4. EVENT ─────── */
    emit WorkflowUpdated(oldWorkflowId, newWorkflowId, msg.sender, rec.donLabel, workflowName);
  }

  /// @dev Reverts if the record does not exist or is not owned by `sender`.
  /// @param sender  Expected owner of the workflow (typically `msg.sender`).
  /// @param rid     Workflow reference-ID (hash of owner ∥ name ∥ tag).
  /// @return workflow  Storage pointer to the requested `WorkflowMetadata`.
  /// @custom:reverts WorkflowDoesNotExist        If no record is found for `rid`.
  /// @custom:reverts CallerIsNotWorkflowOwner    If `sender` ≠ `workflow.owner`.
  function _getWorkflowFromStorage(
    address sender,
    bytes32 rid
  ) internal view returns (WorkflowMetadata storage workflow) {
    workflow = s_workflows[rid];

    if (workflow.owner == address(0)) revert WorkflowDoesNotExist();
    if (workflow.owner != sender) revert CallerIsNotWorkflowOwner(sender);

    return workflow;
  }

  function pauseWorkflow(
    bytes32 workflowId
  ) external {
    _requireOwnerLinked(msg.sender);
    _pauseWorkflow(msg.sender, s_idToRid[workflowId]);
  }

  function activateWorkflow(
    bytes32 workflowId
  ) external {
    _requireOwnerLinked(msg.sender);
    _activateWorkflow(msg.sender, s_idToRid[workflowId]);
  }

  /// @notice Pauses multiple workflows owned by `msg.sender`.
  /// @dev    There is no enforced batch size limit here.
  ///         **User Risk:** Submitting a very large array of `workflowIds`
  ///         may cause the transaction to run out of gas and revert.
  ///         Clients should cap the array length to a safe value based on the current gas limits.
  /// @param  workflowIds Array of workflow IDs to pause; must not be empty.
  function pauseWorkflows(
    bytes32[] calldata workflowIds
  ) external {
    uint256 n = workflowIds.length;
    if (n == 0) revert EmptyUpdateBatch();

    _requireOwnerLinked(msg.sender);

    for (uint256 i = 0; i < n; ++i) {
      bytes32 rid = s_idToRid[workflowIds[i]];
      _pauseWorkflow(msg.sender, rid);
    }
  }

  /// @notice Activate many paused workflows owned by `msg.sender`.
  /// @dev    Performs a full dry-run first:
  ///         - Checks ownership and that each workflow is currently PAUSED.
  ///         - Skips already-ACTIVE IDs when calculating deltas.
  ///         - Calculates net per-DON increments and enforces the global DON cap
  ///           and the per-user-per-DON cap.
  ///         If any check fails, the entire call reverts with no state changes.

  ///         There is no enforced batch size limit here.
  ///         Supplying a very large `workflowIds` array may exhaust block gas limits and cause the transaction to revert.
  ///         Clients should cap the array length to a safe value based on current gas constraints.
  /// @param  workflowIds Array of workflow IDs to activate; must not be empty.
  function batchActivateWorkflows(
    bytes32[] calldata workflowIds
  ) external {
    uint256 n = workflowIds.length;
    if (n == 0) revert EmptyUpdateBatch();

    _requireOwnerLinked(msg.sender);

    // ----- per-DON deltas
    bytes32[] memory dons = new bytes32[](n);
    uint32[] memory inc = new uint32[](n);
    uint256 unique = 0;

    for (uint256 i; i < n; ++i) {
      bytes32 rid = s_idToRid[workflowIds[i]];
      WorkflowMetadata storage rec = _getWorkflowFromStorage(msg.sender, rid);
      if (rec.status == WorkflowStatus.ACTIVE) continue;

      // accumulate
      bytes32 don = rec.donLabel;
      bool found = false;
      for (uint256 j; j < unique; ++j) {
        if (dons[j] == don) {
          ++inc[j];
          found = true;
          break;
        }
      }
      if (!found) {
        dons[unique] = don;
        inc[unique] = 1;
        ++unique;
      }
    }

    // ----- cap checks
    for (uint256 k; k < unique; ++k) {
      bytes32 don = dons[k];
      uint32 add = inc[k];
      if (s_activeDONWorkflowRids[don].length() + add > getMaxWorkflowsPerDON(don)) {
        revert MaxWorkflowsPerDONExceeded(don);
      }
      if (s_userDONCount[msg.sender][don] + add > getMaxWorkflowsPerUserDON(msg.sender, don)) {
        revert MaxWorkflowsPerUserDONExceeded(msg.sender, don);
      }
    }

    // ----- mutations
    for (uint256 i; i < n; ++i) {
      bytes32 rid = s_idToRid[workflowIds[i]];
      // We are not using _activateWorkflow here because we already ownership, status checks,
      // and per-DON/user limits have all been validated.
      WorkflowMetadata storage rec = _getWorkflowFromStorage(msg.sender, rid);
      if (rec.status == WorkflowStatus.PAUSED) {
        _applyActivate(rid, rec);
      }
    }
  }

  /// @notice Internal helper to pause a single workflow, enforcing ownership.
  /// @dev    Performs the following steps in order:
  ///            1. Load the workflow and validate existence & ownership via `_getWorkflowFromStorage`.
  ///            2. Revert if its status is already `PAUSED`, preventing redundant calls.
  ///            3. Apply the pause change by calling `_applyPause`.
  /// @param  rid  The workflow reference ID of the workflow record to pause.
  /// @param  owner The address of the owner of the workflow.
  function _pauseWorkflow(address owner, bytes32 rid) internal {
    WorkflowMetadata storage rec = _getWorkflowFromStorage(owner, rid);
    if (rec.status == WorkflowStatus.PAUSED) {
      revert WorkflowAlreadyInDesiredStatus();
    }
    _applyPause(rid, rec);
  }

  /// @notice Internal helper to activate a single workflow, enforcing ownership and limits.
  /// @dev    Performs the following steps in order:
  ///            1. Load the workflow and validate existence & ownership via `_getWorkflowFromStorage`.
  ///            2. Revert if its status is already `ACTIVE`, preventing redundant calls.
  ///            3. Enforce the global DON cap and per-user-per-DON cap via `_enforceLimits`.
  ///            4. Apply the activation change by calling `_applyActivate`.
  /// @param  rid  The workflow reference ID of the workflow record to pause.
  /// @param  owner The address of the owner of the workflow.
  function _activateWorkflow(address owner, bytes32 rid) internal {
    WorkflowMetadata storage rec = _getWorkflowFromStorage(owner, rid);
    if (rec.status == WorkflowStatus.ACTIVE) {
      revert WorkflowAlreadyInDesiredStatus();
    }
    _enforceLimits(owner, rec.donLabel);
    _applyActivate(rid, rec);
  }

  /// @dev   Apply the state transition PAUSED ➜ ACTIVE.
  /// @param rid  Registry-internal reference id (owner ∥ name ∥ tag).
  /// @param rec  Storage pointer to the workflow metadata.
  /// @notice *NO CHECKS* – caller must guarantee
  ///         • `rec.status == WorkflowStatus.PAUSED`
  ///         • DON/user caps have been enforced already.
  ///         • Caller can perform action.
  function _applyActivate(bytes32 rid, WorkflowMetadata storage rec) private {
    s_userDONCount[rec.owner][rec.donLabel] += 1;
    s_activeDONWorkflowRids[rec.donLabel].add(rid);
    s_activeOwnerWorkflowRids[rec.owner].add(rid);
    s_activeRidsByWorkflowKey[_workflowKey(rec.owner, rec.workflowName)].add(rid);

    rec.status = WorkflowStatus.ACTIVE;
    _pushWorkflowAdded(rec.workflowId, rec.owner, rec.donLabel, rec.workflowName);
  }

  /// @dev   Apply the state transition ACTIVE ➜ PAUSED.
  /// @notice No guards – caller must guarantee that:
  ///         • `rec.status == WorkflowStatus.ACTIVE`
  ///         • Any permission or limit logic has already been handled.
  /// @param  rid   Registry-internal reference ID (owner ∥ name ∥ tag hash).
  /// @param  rec   Storage pointer to the workflow metadata struct.
  function _applyPause(bytes32 rid, WorkflowMetadata storage rec) private {
    s_userDONCount[rec.owner][rec.donLabel] -= 1;
    s_activeDONWorkflowRids[rec.donLabel].remove(rid);
    s_activeOwnerWorkflowRids[rec.owner].remove(rid);
    s_activeRidsByWorkflowKey[_workflowKey(rec.owner, rec.workflowName)].remove(rid);

    rec.status = WorkflowStatus.PAUSED;
    _pushWorkflowRemoved(rec.workflowId, rec.owner, rec.donLabel, rec.workflowName);
  }

  /// @notice Pause all **active** workflow that shares `workflowKey`.
  /// @dev
  ///  * Iterates from the end of `s_activeRidsByWorkflowKey[workflowKey]`
  ///    so the index is never invalidated by `remove`.
  ///  * Removes each paused record from all active-tracking indices and
  ///    decrements `s_userDONCount`.
  ///  * Emits `WorkflowPaused` for every workflow paused.
  ///  * No-op when ≤ 1 active workflow exists for the key.
  ///
  /// @param workflowKey keccak256(owner, workflowName) identifying the
  ///                    workflow family.
  function _pauseAllActiveWorkflowsByWorkflowKey(
    bytes32 workflowKey
  ) internal {
    EnumerableSet.Bytes32Set storage activeSet = s_activeRidsByWorkflowKey[workflowKey];

    // Walk from the back since EnumerableSet.remove is a swap and pop.
    while (activeSet.length() > 1) {
      uint256 lastIdx = activeSet.length() - 1;
      bytes32 rid = activeSet.at(lastIdx);
      WorkflowMetadata storage wf = s_workflows[rid];

      // Update workflow state
      wf.status = WorkflowStatus.PAUSED;
      s_userDONCount[wf.owner][wf.donLabel] -= 1;

      // Remove from active indices
      s_activeOwnerWorkflowRids[wf.owner].remove(rid);
      s_activeDONWorkflowRids[wf.donLabel].remove(rid);
      s_activeRidsByWorkflowKey[workflowKey].remove(rid);

      // Emit event
      emit WorkflowPaused(wf.workflowId, wf.owner, wf.donLabel, wf.workflowName);
    }
  }

  /// @notice Permanently delete a workflow owned by the caller.
  /// @dev Sequence:
  ///  1. Resolve the registry-ID (`rid`) from `workflowId` and verify ownership.
  ///  2. If the workflow is **ACTIVE**, remove it from every
  ///     “active” index and decrement per-DON counters.
  ///  3. Purge the RID from global owner / DON maps and key-based sets.
  ///  4. Clear the ID→RID map, delete the primary record, and emit an event.
  ///  5. Unlinked owners can still delete their workflows.
  ///
  /// @param workflowId  The globally-unique identifier to remove.
  /// @custom:reverts WorkflowDoesNotExist      If the ID is unknown.
  /// @custom:reverts CallerIsNotWorkflowOwner  If `msg.sender` is not the owner.
  function deleteWorkflow(
    bytes32 workflowId
  ) external {
    bytes32 rid = s_idToRid[workflowId];
    _deleteWorkflow(msg.sender, rid);
  }

  function _deleteWorkflow(address owner, bytes32 rid) internal {
    WorkflowMetadata storage rec = _getWorkflowFromStorage(owner, rid);
    if (rec.status == WorkflowStatus.ACTIVE) {
      _deleteActiveIndices(rid, owner, rec.donLabel, _workflowKey(owner, rec.workflowName));
    }
    _applyDelete(rid, rec);
  }

  /// @dev Removes a workflow’s RID from **all “active” indices** and
  ///      decrements the per-user per-DON counter.
  ///
  /// @notice Caller **must** ensure the workflow is currently
  ///         `WorkflowStatus.ACTIVE`; this helper performs no status
  ///         check on its own.
  ///
  /// @param rid          Registry-internal reference ID of the workflow.
  /// @param owner        Workflow owner address.
  /// @param donLabel     DON label the workflow belongs to.
  /// @param workflowKey  keccak256(owner, workflowName) key used for the
  ///                     active-by-name index.
  function _deleteActiveIndices(bytes32 rid, address owner, bytes32 donLabel, bytes32 workflowKey) private {
    s_activeOwnerWorkflowRids[owner].remove(rid);
    s_activeDONWorkflowRids[donLabel].remove(rid);
    s_userDONCount[owner][donLabel] -= 1;
    s_activeRidsByWorkflowKey[workflowKey].remove(rid);
  }

  /// @notice This helper **assumes** all higher-level checks have
  ///         already been performed.
  ///         It does **NOT**
  ///         - verify that `msg.sender` is the workflow owner, nor
  ///         - touch the “active” secondary indices (`s_active*`)
  ///           because the caller is expected to handle this separately
  ///
  /// @param rid  Registry-internal reference ID (hash(owner, name, tag)).
  /// @param rec  Storage pointer to the workflow metadata struct that
  ///             corresponds to `rid`.  Must still be in `PAUSED` state
  ///             (or at least already removed from active counters).
  function _applyDelete(bytes32 rid, WorkflowMetadata storage rec) private {
    s_allDONRids[rec.donLabel].remove(rid);
    s_allOwnerRids[rec.owner].remove(rid);
    s_workflowKeyToRids[_workflowKey(rec.owner, rec.workflowName)].remove(rid);
    delete s_idToRid[rec.workflowId];

    emit WorkflowDeleted(rec.workflowId, rec.owner, rec.donLabel, rec.workflowName);
    delete s_workflows[rid];
  }

  // ================================================================
  // |                       Admin Workflow                         |
  // ================================================================
  function adminPauseWorkflow(
    bytes32 workflowId
  ) public onlyOwner {
    bytes32 rid = s_idToRid[workflowId];
    WorkflowMetadata storage rec = s_workflows[rid]; // no msg.sender check when fetched directly from mapping
    if (rec.status == WorkflowStatus.ACTIVE) {
      _applyPause(rid, rec);
    }
  }

  // @notice Pauses a batch of workflows as an admin, bypassing workflow ownership checks.
  /// @dev    - Only the contract owner may call this function (enforced by `onlyOwner`).
  ///         - Reverts if `workflowIds` is empty to prevent no-op transactions.
  ///         - Iterates over each provided ID and calls `adminPauseWorkflow`, which itself
  ///           verifies the workflow is active before pausing.
  ///         - Beware: supplying an excessively large array may exhaust gas and revert.
  /// @param  workflowIds  Array of globally-unique workflow IDs to pause; must contain at least one element.
  function adminBatchPauseWorkflows(
    bytes32[] calldata workflowIds
  ) external {
    uint256 n = workflowIds.length;
    if (n == 0) revert EmptyUpdateBatch();

    for (uint256 i; i < n; ++i) {
      adminPauseWorkflow(workflowIds[i]);
    }
  }

  /// @notice Pauses *all* active workflows for a given user, as an administrator.
  /// @dev    - Only the contract owner may call this (`onlyOwner`).
  ///         - Iterates from the end of the user’s active-workflow set and directly pauses each workflow.
  /// @param  user The address whose active workflows should be paused.
  function adminPauseAllByUser(
    address user
  ) external onlyOwner {
    EnumerableSet.Bytes32Set storage activeSet = s_activeOwnerWorkflowRids[user];

    // Loop until the set is empty, always pausing the last element. We also know that all workflows in the list are active.
    while (activeSet.length() > 0) {
      bytes32 rid = activeSet.at(activeSet.length() - 1);
      WorkflowMetadata storage rec = s_workflows[rid]; // no msg.sender check when fetched directly from mapping
      _applyPause(rid, rec);
    }
  }

  /// @notice Pauses *all* active workflows under a specific DON label, as an administrator.
  /// @dev    - Only the contract owner may call this (`onlyOwner`).
  ///         - Iterates from the end of the DON’s active-workflow set and directly pauses each workflow.
  /// @param  donLabel The `bytes32` identifier of the DON whose active workflows should be paused.
  function adminPauseAllByDON(
    bytes32 donLabel
  ) external onlyOwner {
    EnumerableSet.Bytes32Set storage activeSet = s_activeDONWorkflowRids[donLabel];

    // Loop until the set is empty, always pausing the last workflow
    while (activeSet.length() > 0) {
      // Grab the RID of the last active workflow
      bytes32 rid = activeSet.at(activeSet.length() - 1);
      // Lookup its external workflowId for the admin pause call
      WorkflowMetadata storage rec = s_workflows[rid];
      adminPauseWorkflow(rec.workflowId);
    }
  }

  // ================================================================
  // |                       Workflow Views                         |
  // ================================================================
  /// @notice Return the full on-chain metadata for a given workflow.
  /// @dev
  /// 1. Looks up the registry-internal reference‐ID (RID) from
  ///    `s_idToRid` using the caller-supplied `workflowId`.
  /// 2. Uses that RID to fetch the packed `WorkflowMetadata` struct.
  /// 3. Reverts with `WorkflowDoesNotExist` if either mapping slot is
  ///    empty (i.e. the workflow was never registered or has been
  ///    deleted).
  ///
  /// @param workflowId Globally-unique, immutable identifier of the
  ///                   workflow (hash of owner, name, binary, cfg, …).
  /// @return workflow      In-memory copy of the workflow’s metadata record.
  ///
  /// @custom:revert WorkflowDoesNotExist  If no RID is found for
  ///                                       `workflowId`, or the RID maps
  ///                                       to an empty metadata record.
  function getWorkflowMetadata(
    bytes32 workflowId
  ) external view returns (WorkflowMetadata memory workflow) {
    bytes32 rid = s_idToRid[workflowId];
    if (rid == bytes32(0)) revert WorkflowDoesNotExist();

    workflow = s_workflows[rid];
    if (workflow.owner == address(0)) revert WorkflowDoesNotExist();
    return workflow;
  }

  /// @notice  Return a paginated list of all versions (active *and* paused)
  ///          of workflows with the same `workflowName` and `owner`.
  /// @dev     Uses the secondary key ⟨owner, workflowName⟩ → RID-set
  ///          (`s_workflowKeyToRids`).  When `limit` is 0 or exceeds
  ///          `MAX_PAGINATION_LIMIT`, the call clamps it to that constant.
  ///          Does **not** revert on out-of-range pagination: if `start` is
  ///          beyond the end of the set the function returns an empty array.
  /// @param   owner         Address that registered the workflows.
  /// @param   workflowName  Case-sensitive name string (≤ 64 chars).
  /// @param   start         Zero-based index into the RID set.
  /// @param   limit         Max #records to return (clamped to 100).
  /// @return  list          Array of `WorkflowMetadata`.
  function getWorkflowMetadataListByOwnerName(
    address owner,
    string calldata workflowName,
    uint256 start,
    uint256 limit
  ) external view returns (WorkflowMetadata[] memory list) {
    bytes32 wKey = _workflowKey(owner, workflowName);
    uint256 total = s_workflowKeyToRids[wKey].length();
    (uint256 offset, uint256 count) = _getPageBounds(total, start, limit);

    list = new WorkflowMetadata[](count);
    for (uint256 i = 0; i < count; ++i) {
      bytes32 rid = s_workflowKeyToRids[wKey].at(offset + i);
      list[i] = s_workflows[rid];
    }

    return list;
  }

  /// @notice Return a paginated slice of all workflows (active + paused)
  ///         owned by a specific address.
  /// @dev
  /// - Reads the RID set `s_allOwnerRids[owner]`, which contains every
  ///   workflow ever registered by `owner`, regardless of status.
  /// - If `start` is ≥ the set’s length the call returns an empty array.
  /// - `limit` is capped to `MAX_PAGINATION_LIMIT` when zero or greater
  ///   than that constant.
  /// - Does not revert on out-of-range pagination; it simply returns the
  ///   largest sub-range that fits inside the set.
  /// @param owner  The address whose workflows are requested.
  /// @param start  Zero-based index into the owner’s RID set.
  /// @param limit  Maximum number of records to return; a value of 0 or
  ///               > `MAX_PAGINATION_LIMIT` is treated as
  ///               `MAX_PAGINATION_LIMIT`.
  /// @return list Array of `WorkflowMetadata` with length
  ///              `min(limit, total-start)`.
  function getWorkflowMetadataListByOwner(
    address owner,
    uint256 start,
    uint256 limit
  ) external view returns (WorkflowMetadata[] memory list) {
    uint256 total = s_allOwnerRids[owner].length();
    (uint256 offset, uint256 count) = _getPageBounds(total, start, limit);

    list = new WorkflowMetadata[](count);
    for (uint256 i = 0; i < count; ++i) {
      bytes32 rid = s_allOwnerRids[owner].at(offset + i);
      list[i] = s_workflows[rid];
    }
    return list;
  }

  /// @notice Fetch a paginated slice of **all** workflows (active *and*
  ///         paused) that belong to a given DON.
  /// @dev
  ///  * Reads the RID set `s_allDONRids[donLabel]`, which tracks every
  ///    workflow ever registered to that DON, regardless of status.
  ///  * If `start` is beyond the set’s length it returns an empty array.
  ///  * Caps `limit` to `MAX_PAGINATION_LIMIT` when the caller supplies
  ///    zero or a value larger than the contract-wide maximum.
  ///  * Does **not** revert on out-of-range requests; instead it returns
  ///    the largest sub-range that fits inside the set.
  ///
  /// @param donLabel  bytes32-encoded DON label used as the secondary key.
  /// @param start     Zero-based index into the RID set.
  /// @param limit     Maximum number of records to return; the call will
  ///                  truncate to `MAX_PAGINATION_LIMIT` if necessary.
  /// @return list     Array of `WorkflowMetadata` structs whose length is
  ///                  `min(limit, total-start)`.
  function getWorkflowMetadataListByDON(
    bytes32 donLabel,
    uint256 start,
    uint256 limit
  ) external view returns (WorkflowMetadata[] memory list) {
    uint256 total = s_allDONRids[donLabel].length();
    (uint256 offset, uint256 count) = _getPageBounds(total, start, limit);

    list = new WorkflowMetadata[](count);
    for (uint256 i = 0; i < count; ++i) {
      bytes32 rid = s_allDONRids[donLabel].at(offset + i);
      list[i] = s_workflows[rid];
    }

    return list;
  }

  /// @dev  Compute a safe `[offset … offset+count)` window over `total` items for pagination.
  ///       - If `start >= total`, returns `(total, 0)`
  ///       - If `limit == 0` or `limit > MAX_PAGINATION_LIMIT`, clamps to `MAX_PAGINATION_LIMIT`
  /// @return offset The (possibly‐clamped) start index
  /// @return count  How many items fit before hitting `total`
  function _getPageBounds(
    uint256 total,
    uint256 start,
    uint256 limit
  ) internal pure returns (uint256 offset, uint256 count) {
    if (start >= total) {
      return (total, 0);
    }
    if (limit == 0 || limit > MAX_PAGINATION_LIMIT) {
      limit = MAX_PAGINATION_LIMIT;
    }
    uint256 end = start + limit;
    if (end > total) {
      end = total;
    }
    return (start, end - start);
  }

  function _enforceLimits(address owner, bytes32 donLabel) internal view {
    if (s_activeDONWorkflowRids[donLabel].length() >= getMaxWorkflowsPerDON(donLabel)) {
      revert MaxWorkflowsPerDONExceeded(donLabel);
    }
    if (s_userDONCount[owner][donLabel] >= getMaxWorkflowsPerUserDON(owner, donLabel)) {
      revert MaxWorkflowsPerUserDONExceeded(owner, donLabel);
    }
  }

  function _validateWorkflowURLs(uint256 binaryLen, uint256 configLen) private pure {
    if (binaryLen > MAX_URL_LENGTH) revert URLTooLong(binaryLen, MAX_URL_LENGTH);
    if (configLen > MAX_URL_LENGTH) revert URLTooLong(configLen, MAX_URL_LENGTH);
  }

  function _validateWorkflowName(
    uint256 nameLen
  ) private pure {
    if (nameLen == 0) revert WorkflowNameRequired();
    if (nameLen > MAX_WORKFLOW_NAME_LENGTH) revert WorkflowNameTooLong(nameLen, MAX_WORKFLOW_NAME_LENGTH);
  }

  /// @notice Ensures the given workflowId is unique and non-zero.
  /// @param workflowId The workflowId to validate and consume.
  function _validateWorkflowID(
    bytes32 workflowId
  ) private view {
    if (workflowId == bytes32(0)) revert ZeroAddressNotAllowed();

    if (s_idToRid[workflowId] != bytes32(0)) {
      revert WorkflowIDAlreadyExists(workflowId);
    }
  }

  function _validateWorkflowTag(
    uint256 tagLen
  ) private pure {
    if (tagLen == 0) revert WorkflowTagRequired();
    if (tagLen > MAX_WORKFLOW_TAG_LENGTH) revert WorkflowTagTooLong(tagLen, MAX_WORKFLOW_TAG_LENGTH);
  }

  function _validateAttributesLength(
    uint256 len
  ) private pure {
    if (len > MAX_ATTRIBUTES_LENGTH) {
      revert AttributesTooLong(len, MAX_ATTRIBUTES_LENGTH);
    }
  }

  function _workflowKey(address owner, string memory name) internal pure returns (bytes32) {
    return keccak256(abi.encode(owner, name));
  }

  function _workflowRid(address owner, string memory name, string memory tag) internal pure returns (bytes32) {
    return keccak256(abi.encode(owner, name, tag));
  }
}
