AutoCreateKey = true
BackupLogPollerBlockDelay = 100
BlockBackfillDepth = 10
BlockBackfillSkip = false
FinalityDepth = 50
FinalityTagEnabled = false
FinalizedBlockOffset = 0
LogBackfillBatchSize = 1000
LogBroadcasterEnabled = true
LogKeepBlocksDepth = 100000
LogPollInterval = '15s'
LogPrunePageSize = 0
MinContractPayment = '.00001 link'
MinIncomingConfirmations = 3
NoNewFinalizedHeadsThreshold = '0'
NoNewHeadsThreshold = '3m'
NonceAutoSync = true
RPCBlockQueryDelay = 1
RPCDefaultBatchSize = 250
SafeDepth = 0

[Transactions]
Enabled = true
ForwardersEnabled = false
MaxInFlight = 16
MaxQueued = 250
ReaperInterval = '1h'
ReaperThreshold = '168h'
ResendAfterThreshold = '1m'

[Transactions.AutoPurge]
Enabled = false

[Transactions.TransactionManagerV2]
Enabled = false

[BalanceMonitor]
Enabled = true

[GasEstimator]
BumpMin = '5 gwei'
BumpPercent = 20
BumpThreshold = 3
EIP1559DynamicFees = false
EstimateLimit = false
FeeCapDefault = '100 gwei'
LimitDefault = 500_000
LimitMax = 500_000
LimitMultiplier = '1'
LimitTransfer = 21_000
Mode = 'BlockHistory'
PriceDefault = '20 gwei'
PriceMax = '115792089237316195423570985008687907853269984665.640564039457584007913129639935 tether'
PriceMin = '1 gwei'
TipCapDefault = '1'
TipCapMin = '1'

[GasEstimator.BlockHistory]
BatchSize = 25
BlockHistorySize = 8
CheckInclusionBlocks = 12
CheckInclusionPercentile = 90
TransactionPercentile = 60

[GasEstimator.FeeHistory]
CacheTimeout = '10s'

[HeadTracker]
FinalityTagBypass = true
HistoryDepth = 100
MaxAllowedFinalityDepth = 10000
MaxBufferSize = 3
PersistenceEnabled = true
SamplingInterval = '1s'

[NodePool]
DeathDeclarationDelay = '1m'
EnforceRepeatableRead = true
FinalizedBlockPollInterval = '5s'
LeaseDuration = '0s'
NewHeadsPollInterval = '0s'
NodeIsSyncingEnabled = false
PollFailureThreshold = 5
PollInterval = '10s'
SelectionMode = 'HighestHead'
SyncThreshold = 5
VerifyChainID = true

[OCR]
ContractConfirmations = 4
ContractTransmitterTransmitTimeout = '10s'
DatabaseTimeout = '10s'
DeltaCJitterOverride = '1h'
DeltaCOverride = '168h'
ObservationGracePeriod = '1s'

[OCR2.Automation]
GasLimit = 5400000

[WriteCapability]
GasLimitDefault = 400_000
TxAcceptanceState = 2
PollPeriod = '2s'
AcceptanceTimeout = '30s'
