ChainID = '296'
ChainType = 'hedera'
# Considering the 3-5 (6 including a buffer) seconds of finality and 2 seconds block production
# We set the depth to 6/2 = 3 blocks, setting to 10 for safety
FinalityDepth = 10
LinkContractAddress = '0x90a386d59b9A6a4795a011e8f032Fc21ED6FEFb6'
# Hedera has high TPS, so polling less often 
LogPollInterval = '10s'
MinIncomingConfirmations = 1
FinalizedBlockOffset = 2

[BalanceMonitor]
Enabled = true

[GasEstimator]
EIP1559DynamicFees = true
Mode = 'FeeHistory'
BumpThreshold = 1 # Force retry after each block.
EstimateLimit = true
LimitTransfer = 21_300
LimitDefault = 200_000
LimitMax = 200_000

[GasEstimator.FeeHistory]
CacheTimeout = '4s'

[GasEstimator.BlockHistory]
# This is used by the FeeHistory estimator in chains that don't have a mempool.
BlockHistorySize = 0

[Transactions.TransactionManagerV2]
Enabled = true
BlockTime = '3s'

[Transactions.AutoPurge]
Enabled = true
Threshold = 5
MinAttempts = 10000


[NodePool]
SyncThreshold = 10