ChainID = '2024'
FinalityDepth = 1
LogBroadcasterEnabled = false
RPCDefaultBatchSize = 10

[BalanceMonitor]
Enabled = false # no gas chain

[GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '0'
PriceMin = '0'
PriceMax = '0'
BumpThreshold = 0
LimitDefault = 250000000
LimitMax = 250000000
FeeCapDefault = '0'
TipCapDefault = '0'
TipCapMin = '0'

[HeadTracker]
PersistenceEnabled = false

[NodePool]
EnforceRepeatableRead = false