#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │    Compiling CRE Core contracts...           │"
echo " └──────────────────────────────────────────────┘"


PROJECT="core"

CONTRACTS_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../ && pwd -P )"
echo "Contracts directory: $CONTRACTS_DIR"

compileContract () {
  export FOUNDRY_PROFILE="$1"

  local src_rel="$2"
  local contract=$(basename "$src_rel")
  echo "Compiling" "$contract"

  forge build "$CONTRACTS_DIR/src/$PROJECT/$src_rel.sol" \
  --root "$CONTRACTS_DIR" \
  --extra-output-files bin abi \
  -o "$CONTRACTS_DIR/solc/$PROJECT/$src_rel"
}

compileContract core-v1 v1/CapabilitiesRegistry
compileContract core-v1 v1/KeystoneForwarder
compileContract core-v1 v1/OCR3Capability
compileContract core-v1 v1/KeystoneFeedsConsumer
compileContract core-v1 v1/BalanceReader
compileContract core-v2 v2/CapabilitiesRegistry
