// Code generated by mockery v2.53.3. DO NOT EDIT.

package txm

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	coretypes "github.com/ethereum/go-ethereum/core/types"

	mock "github.com/stretchr/testify/mock"

	types "github.com/smartcontractkit/chainlink-evm/pkg/txm/types"
)

// MockTxStore is an autogenerated mock type for the TxStore type
type MockTxStore struct {
	mock.Mock
}

type MockTxStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxStore) EXPECT() *MockTxStore_Expecter {
	return &MockTxStore_Expecter{mock: &_m.Mock}
}

// AbandonPendingTransactions provides a mock function with given fields: _a0, _a1
func (_m *MockTxStore) AbandonPendingTransactions(_a0 context.Context, _a1 common.Address) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AbandonPendingTransactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxStore_AbandonPendingTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbandonPendingTransactions'
type MockTxStore_AbandonPendingTransactions_Call struct {
	*mock.Call
}

// AbandonPendingTransactions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 common.Address
func (_e *MockTxStore_Expecter) AbandonPendingTransactions(_a0 interface{}, _a1 interface{}) *MockTxStore_AbandonPendingTransactions_Call {
	return &MockTxStore_AbandonPendingTransactions_Call{Call: _e.mock.On("AbandonPendingTransactions", _a0, _a1)}
}

func (_c *MockTxStore_AbandonPendingTransactions_Call) Run(run func(_a0 context.Context, _a1 common.Address)) *MockTxStore_AbandonPendingTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_AbandonPendingTransactions_Call) Return(_a0 error) *MockTxStore_AbandonPendingTransactions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_AbandonPendingTransactions_Call) RunAndReturn(run func(context.Context, common.Address) error) *MockTxStore_AbandonPendingTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// AppendAttemptToTransaction provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockTxStore) AppendAttemptToTransaction(_a0 context.Context, _a1 uint64, _a2 common.Address, _a3 *types.Attempt) ([]*types.Attempt, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for AppendAttemptToTransaction")
	}

	var r0 []*types.Attempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address, *types.Attempt) ([]*types.Attempt, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address, *types.Attempt) []*types.Attempt); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Attempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, common.Address, *types.Attempt) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTxStore_AppendAttemptToTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendAttemptToTransaction'
type MockTxStore_AppendAttemptToTransaction_Call struct {
	*mock.Call
}

// AppendAttemptToTransaction is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
//   - _a2 common.Address
//   - _a3 *types.Attempt
func (_e *MockTxStore_Expecter) AppendAttemptToTransaction(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockTxStore_AppendAttemptToTransaction_Call {
	return &MockTxStore_AppendAttemptToTransaction_Call{Call: _e.mock.On("AppendAttemptToTransaction", _a0, _a1, _a2, _a3)}
}

func (_c *MockTxStore_AppendAttemptToTransaction_Call) Run(run func(_a0 context.Context, _a1 uint64, _a2 common.Address, _a3 *types.Attempt)) *MockTxStore_AppendAttemptToTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(common.Address), args[3].(*types.Attempt))
	})
	return _c
}

func (_c *MockTxStore_AppendAttemptToTransaction_Call) Return(attempts []*types.Attempt, err error) *MockTxStore_AppendAttemptToTransaction_Call {
	_c.Call.Return(attempts, err)
	return _c
}

func (_c *MockTxStore_AppendAttemptToTransaction_Call) RunAndReturn(run func(context.Context, uint64, common.Address, *types.Attempt) ([]*types.Attempt, error)) *MockTxStore_AppendAttemptToTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEmptyUnconfirmedTransaction provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockTxStore) CreateEmptyUnconfirmedTransaction(_a0 context.Context, _a1 common.Address, _a2 uint64, _a3 uint64) (*types.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmptyUnconfirmedTransaction")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint64, uint64) (*types.Transaction, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint64, uint64) *types.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, uint64, uint64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTxStore_CreateEmptyUnconfirmedTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEmptyUnconfirmedTransaction'
type MockTxStore_CreateEmptyUnconfirmedTransaction_Call struct {
	*mock.Call
}

// CreateEmptyUnconfirmedTransaction is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 common.Address
//   - _a2 uint64
//   - _a3 uint64
func (_e *MockTxStore_Expecter) CreateEmptyUnconfirmedTransaction(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockTxStore_CreateEmptyUnconfirmedTransaction_Call {
	return &MockTxStore_CreateEmptyUnconfirmedTransaction_Call{Call: _e.mock.On("CreateEmptyUnconfirmedTransaction", _a0, _a1, _a2, _a3)}
}

func (_c *MockTxStore_CreateEmptyUnconfirmedTransaction_Call) Run(run func(_a0 context.Context, _a1 common.Address, _a2 uint64, _a3 uint64)) *MockTxStore_CreateEmptyUnconfirmedTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(uint64), args[3].(uint64))
	})
	return _c
}

func (_c *MockTxStore_CreateEmptyUnconfirmedTransaction_Call) Return(_a0 *types.Transaction, _a1 error) *MockTxStore_CreateEmptyUnconfirmedTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTxStore_CreateEmptyUnconfirmedTransaction_Call) RunAndReturn(run func(context.Context, common.Address, uint64, uint64) (*types.Transaction, error)) *MockTxStore_CreateEmptyUnconfirmedTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransaction provides a mock function with given fields: _a0, _a1
func (_m *MockTxStore) CreateTransaction(_a0 context.Context, _a1 *types.TxRequest) (*types.Transaction, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.TxRequest) (*types.Transaction, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.TxRequest) *types.Transaction); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.TxRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTxStore_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockTxStore_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *types.TxRequest
func (_e *MockTxStore_Expecter) CreateTransaction(_a0 interface{}, _a1 interface{}) *MockTxStore_CreateTransaction_Call {
	return &MockTxStore_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", _a0, _a1)}
}

func (_c *MockTxStore_CreateTransaction_Call) Run(run func(_a0 context.Context, _a1 *types.TxRequest)) *MockTxStore_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.TxRequest))
	})
	return _c
}

func (_c *MockTxStore_CreateTransaction_Call) Return(_a0 *types.Transaction, _a1 error) *MockTxStore_CreateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTxStore_CreateTransaction_Call) RunAndReturn(run func(context.Context, *types.TxRequest) (*types.Transaction, error)) *MockTxStore_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttemptForUnconfirmedTx provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockTxStore) DeleteAttemptForUnconfirmedTx(_a0 context.Context, _a1 uint64, _a2 *types.Attempt, _a3 common.Address) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttemptForUnconfirmedTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, *types.Attempt, common.Address) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxStore_DeleteAttemptForUnconfirmedTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttemptForUnconfirmedTx'
type MockTxStore_DeleteAttemptForUnconfirmedTx_Call struct {
	*mock.Call
}

// DeleteAttemptForUnconfirmedTx is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
//   - _a2 *types.Attempt
//   - _a3 common.Address
func (_e *MockTxStore_Expecter) DeleteAttemptForUnconfirmedTx(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockTxStore_DeleteAttemptForUnconfirmedTx_Call {
	return &MockTxStore_DeleteAttemptForUnconfirmedTx_Call{Call: _e.mock.On("DeleteAttemptForUnconfirmedTx", _a0, _a1, _a2, _a3)}
}

func (_c *MockTxStore_DeleteAttemptForUnconfirmedTx_Call) Run(run func(_a0 context.Context, _a1 uint64, _a2 *types.Attempt, _a3 common.Address)) *MockTxStore_DeleteAttemptForUnconfirmedTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(*types.Attempt), args[3].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_DeleteAttemptForUnconfirmedTx_Call) Return(_a0 error) *MockTxStore_DeleteAttemptForUnconfirmedTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_DeleteAttemptForUnconfirmedTx_Call) RunAndReturn(run func(context.Context, uint64, *types.Attempt, common.Address) error) *MockTxStore_DeleteAttemptForUnconfirmedTx_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUnconfirmedTransactionAtNonceWithCount provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockTxStore) FetchUnconfirmedTransactionAtNonceWithCount(_a0 context.Context, _a1 uint64, _a2 common.Address) (*types.Transaction, int, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for FetchUnconfirmedTransactionAtNonceWithCount")
	}

	var r0 *types.Transaction
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address) (*types.Transaction, int, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address) *types.Transaction); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, common.Address) int); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, common.Address) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUnconfirmedTransactionAtNonceWithCount'
type MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call struct {
	*mock.Call
}

// FetchUnconfirmedTransactionAtNonceWithCount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
//   - _a2 common.Address
func (_e *MockTxStore_Expecter) FetchUnconfirmedTransactionAtNonceWithCount(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call {
	return &MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call{Call: _e.mock.On("FetchUnconfirmedTransactionAtNonceWithCount", _a0, _a1, _a2)}
}

func (_c *MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call) Run(run func(_a0 context.Context, _a1 uint64, _a2 common.Address)) *MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call) Return(_a0 *types.Transaction, _a1 int, _a2 error) *MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call) RunAndReturn(run func(context.Context, uint64, common.Address) (*types.Transaction, int, error)) *MockTxStore_FetchUnconfirmedTransactionAtNonceWithCount_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUnconfirmedTransactions provides a mock function with given fields: _a0, _a1
func (_m *MockTxStore) FetchUnconfirmedTransactions(_a0 context.Context, _a1 common.Address) ([]*types.Transaction, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FetchUnconfirmedTransactions")
	}

	var r0 []*types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) ([]*types.Transaction, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) []*types.Transaction); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTxStore_FetchUnconfirmedTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUnconfirmedTransactions'
type MockTxStore_FetchUnconfirmedTransactions_Call struct {
	*mock.Call
}

// FetchUnconfirmedTransactions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 common.Address
func (_e *MockTxStore_Expecter) FetchUnconfirmedTransactions(_a0 interface{}, _a1 interface{}) *MockTxStore_FetchUnconfirmedTransactions_Call {
	return &MockTxStore_FetchUnconfirmedTransactions_Call{Call: _e.mock.On("FetchUnconfirmedTransactions", _a0, _a1)}
}

func (_c *MockTxStore_FetchUnconfirmedTransactions_Call) Run(run func(_a0 context.Context, _a1 common.Address)) *MockTxStore_FetchUnconfirmedTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_FetchUnconfirmedTransactions_Call) Return(_a0 []*types.Transaction, _a1 error) *MockTxStore_FetchUnconfirmedTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTxStore_FetchUnconfirmedTransactions_Call) RunAndReturn(run func(context.Context, common.Address) ([]*types.Transaction, error)) *MockTxStore_FetchUnconfirmedTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// MarkConfirmedAndReorgedTransactions provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockTxStore) MarkConfirmedAndReorgedTransactions(_a0 context.Context, _a1 uint64, _a2 common.Address) ([]*types.Transaction, []uint64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MarkConfirmedAndReorgedTransactions")
	}

	var r0 []*types.Transaction
	var r1 []uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address) ([]*types.Transaction, []uint64, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address) []*types.Transaction); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, common.Address) []uint64); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]uint64)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, common.Address) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTxStore_MarkConfirmedAndReorgedTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkConfirmedAndReorgedTransactions'
type MockTxStore_MarkConfirmedAndReorgedTransactions_Call struct {
	*mock.Call
}

// MarkConfirmedAndReorgedTransactions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
//   - _a2 common.Address
func (_e *MockTxStore_Expecter) MarkConfirmedAndReorgedTransactions(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockTxStore_MarkConfirmedAndReorgedTransactions_Call {
	return &MockTxStore_MarkConfirmedAndReorgedTransactions_Call{Call: _e.mock.On("MarkConfirmedAndReorgedTransactions", _a0, _a1, _a2)}
}

func (_c *MockTxStore_MarkConfirmedAndReorgedTransactions_Call) Run(run func(_a0 context.Context, _a1 uint64, _a2 common.Address)) *MockTxStore_MarkConfirmedAndReorgedTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_MarkConfirmedAndReorgedTransactions_Call) Return(_a0 []*types.Transaction, _a1 []uint64, _a2 error) *MockTxStore_MarkConfirmedAndReorgedTransactions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTxStore_MarkConfirmedAndReorgedTransactions_Call) RunAndReturn(run func(context.Context, uint64, common.Address) ([]*types.Transaction, []uint64, error)) *MockTxStore_MarkConfirmedAndReorgedTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTxFatal provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockTxStore) MarkTxFatal(_a0 context.Context, _a1 *types.Transaction, _a2 common.Address) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MarkTxFatal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.Transaction, common.Address) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxStore_MarkTxFatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTxFatal'
type MockTxStore_MarkTxFatal_Call struct {
	*mock.Call
}

// MarkTxFatal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *types.Transaction
//   - _a2 common.Address
func (_e *MockTxStore_Expecter) MarkTxFatal(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockTxStore_MarkTxFatal_Call {
	return &MockTxStore_MarkTxFatal_Call{Call: _e.mock.On("MarkTxFatal", _a0, _a1, _a2)}
}

func (_c *MockTxStore_MarkTxFatal_Call) Run(run func(_a0 context.Context, _a1 *types.Transaction, _a2 common.Address)) *MockTxStore_MarkTxFatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.Transaction), args[2].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_MarkTxFatal_Call) Return(_a0 error) *MockTxStore_MarkTxFatal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_MarkTxFatal_Call) RunAndReturn(run func(context.Context, *types.Transaction, common.Address) error) *MockTxStore_MarkTxFatal_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUnconfirmedTransactionPurgeable provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockTxStore) MarkUnconfirmedTransactionPurgeable(_a0 context.Context, _a1 uint64, _a2 common.Address) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MarkUnconfirmedTransactionPurgeable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxStore_MarkUnconfirmedTransactionPurgeable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUnconfirmedTransactionPurgeable'
type MockTxStore_MarkUnconfirmedTransactionPurgeable_Call struct {
	*mock.Call
}

// MarkUnconfirmedTransactionPurgeable is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
//   - _a2 common.Address
func (_e *MockTxStore_Expecter) MarkUnconfirmedTransactionPurgeable(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockTxStore_MarkUnconfirmedTransactionPurgeable_Call {
	return &MockTxStore_MarkUnconfirmedTransactionPurgeable_Call{Call: _e.mock.On("MarkUnconfirmedTransactionPurgeable", _a0, _a1, _a2)}
}

func (_c *MockTxStore_MarkUnconfirmedTransactionPurgeable_Call) Run(run func(_a0 context.Context, _a1 uint64, _a2 common.Address)) *MockTxStore_MarkUnconfirmedTransactionPurgeable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_MarkUnconfirmedTransactionPurgeable_Call) Return(_a0 error) *MockTxStore_MarkUnconfirmedTransactionPurgeable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_MarkUnconfirmedTransactionPurgeable_Call) RunAndReturn(run func(context.Context, uint64, common.Address) error) *MockTxStore_MarkUnconfirmedTransactionPurgeable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSignedAttempt provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockTxStore) UpdateSignedAttempt(_a0 context.Context, _a1 uint64, _a2 uint64, _a3 *coretypes.Transaction, _a4 common.Address) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSignedAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, *coretypes.Transaction, common.Address) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxStore_UpdateSignedAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSignedAttempt'
type MockTxStore_UpdateSignedAttempt_Call struct {
	*mock.Call
}

// UpdateSignedAttempt is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
//   - _a2 uint64
//   - _a3 *coretypes.Transaction
//   - _a4 common.Address
func (_e *MockTxStore_Expecter) UpdateSignedAttempt(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockTxStore_UpdateSignedAttempt_Call {
	return &MockTxStore_UpdateSignedAttempt_Call{Call: _e.mock.On("UpdateSignedAttempt", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockTxStore_UpdateSignedAttempt_Call) Run(run func(_a0 context.Context, _a1 uint64, _a2 uint64, _a3 *coretypes.Transaction, _a4 common.Address)) *MockTxStore_UpdateSignedAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(*coretypes.Transaction), args[4].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_UpdateSignedAttempt_Call) Return(_a0 error) *MockTxStore_UpdateSignedAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_UpdateSignedAttempt_Call) RunAndReturn(run func(context.Context, uint64, uint64, *coretypes.Transaction, common.Address) error) *MockTxStore_UpdateSignedAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransactionBroadcast provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockTxStore) UpdateTransactionBroadcast(_a0 context.Context, _a1 uint64, _a2 uint64, _a3 common.Hash, _a4 common.Address) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionBroadcast")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, common.Hash, common.Address) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxStore_UpdateTransactionBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransactionBroadcast'
type MockTxStore_UpdateTransactionBroadcast_Call struct {
	*mock.Call
}

// UpdateTransactionBroadcast is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
//   - _a2 uint64
//   - _a3 common.Hash
//   - _a4 common.Address
func (_e *MockTxStore_Expecter) UpdateTransactionBroadcast(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockTxStore_UpdateTransactionBroadcast_Call {
	return &MockTxStore_UpdateTransactionBroadcast_Call{Call: _e.mock.On("UpdateTransactionBroadcast", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockTxStore_UpdateTransactionBroadcast_Call) Run(run func(_a0 context.Context, _a1 uint64, _a2 uint64, _a3 common.Hash, _a4 common.Address)) *MockTxStore_UpdateTransactionBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(common.Hash), args[4].(common.Address))
	})
	return _c
}

func (_c *MockTxStore_UpdateTransactionBroadcast_Call) Return(_a0 error) *MockTxStore_UpdateTransactionBroadcast_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_UpdateTransactionBroadcast_Call) RunAndReturn(run func(context.Context, uint64, uint64, common.Hash, common.Address) error) *MockTxStore_UpdateTransactionBroadcast_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUnstartedTransactionWithNonce provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockTxStore) UpdateUnstartedTransactionWithNonce(_a0 context.Context, _a1 common.Address, _a2 uint64) (*types.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUnstartedTransactionWithNonce")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint64) (*types.Transaction, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint64) *types.Transaction); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, uint64) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTxStore_UpdateUnstartedTransactionWithNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUnstartedTransactionWithNonce'
type MockTxStore_UpdateUnstartedTransactionWithNonce_Call struct {
	*mock.Call
}

// UpdateUnstartedTransactionWithNonce is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 common.Address
//   - _a2 uint64
func (_e *MockTxStore_Expecter) UpdateUnstartedTransactionWithNonce(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockTxStore_UpdateUnstartedTransactionWithNonce_Call {
	return &MockTxStore_UpdateUnstartedTransactionWithNonce_Call{Call: _e.mock.On("UpdateUnstartedTransactionWithNonce", _a0, _a1, _a2)}
}

func (_c *MockTxStore_UpdateUnstartedTransactionWithNonce_Call) Run(run func(_a0 context.Context, _a1 common.Address, _a2 uint64)) *MockTxStore_UpdateUnstartedTransactionWithNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(uint64))
	})
	return _c
}

func (_c *MockTxStore_UpdateUnstartedTransactionWithNonce_Call) Return(_a0 *types.Transaction, _a1 error) *MockTxStore_UpdateUnstartedTransactionWithNonce_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTxStore_UpdateUnstartedTransactionWithNonce_Call) RunAndReturn(run func(context.Context, common.Address, uint64) (*types.Transaction, error)) *MockTxStore_UpdateUnstartedTransactionWithNonce_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxStore creates a new instance of MockTxStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxStore {
	mock := &MockTxStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
