// Code generated by mockery v2.53.3. DO NOT EDIT.

package txm

import (
	context "context"

	logger "github.com/smartcontractkit/chainlink-common/pkg/logger"
	mock "github.com/stretchr/testify/mock"

	types "github.com/smartcontractkit/chainlink-evm/pkg/txm/types"
)

// mockAttemptBuilder is an autogenerated mock type for the AttemptBuilder type
type mockAttemptBuilder struct {
	mock.Mock
}

type mockAttemptBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAttemptBuilder) EXPECT() *mockAttemptBuilder_Expecter {
	return &mockAttemptBuilder_Expecter{mock: &_m.Mock}
}

// NewAgnosticBumpAttempt provides a mock function with given fields: ctx, lggr, tx, dynamic
func (_m *mockAttemptBuilder) NewAgnosticBumpAttempt(ctx context.Context, lggr logger.Logger, tx *types.Transaction, dynamic bool) (*types.Attempt, error) {
	ret := _m.Called(ctx, lggr, tx, dynamic)

	if len(ret) == 0 {
		panic("no return value specified for NewAgnosticBumpAttempt")
	}

	var r0 *types.Attempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, logger.Logger, *types.Transaction, bool) (*types.Attempt, error)); ok {
		return rf(ctx, lggr, tx, dynamic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, logger.Logger, *types.Transaction, bool) *types.Attempt); ok {
		r0 = rf(ctx, lggr, tx, dynamic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Attempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, logger.Logger, *types.Transaction, bool) error); ok {
		r1 = rf(ctx, lggr, tx, dynamic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAttemptBuilder_NewAgnosticBumpAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAgnosticBumpAttempt'
type mockAttemptBuilder_NewAgnosticBumpAttempt_Call struct {
	*mock.Call
}

// NewAgnosticBumpAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - lggr logger.Logger
//   - tx *types.Transaction
//   - dynamic bool
func (_e *mockAttemptBuilder_Expecter) NewAgnosticBumpAttempt(ctx interface{}, lggr interface{}, tx interface{}, dynamic interface{}) *mockAttemptBuilder_NewAgnosticBumpAttempt_Call {
	return &mockAttemptBuilder_NewAgnosticBumpAttempt_Call{Call: _e.mock.On("NewAgnosticBumpAttempt", ctx, lggr, tx, dynamic)}
}

func (_c *mockAttemptBuilder_NewAgnosticBumpAttempt_Call) Run(run func(ctx context.Context, lggr logger.Logger, tx *types.Transaction, dynamic bool)) *mockAttemptBuilder_NewAgnosticBumpAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(logger.Logger), args[2].(*types.Transaction), args[3].(bool))
	})
	return _c
}

func (_c *mockAttemptBuilder_NewAgnosticBumpAttempt_Call) Return(_a0 *types.Attempt, _a1 error) *mockAttemptBuilder_NewAgnosticBumpAttempt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAttemptBuilder_NewAgnosticBumpAttempt_Call) RunAndReturn(run func(context.Context, logger.Logger, *types.Transaction, bool) (*types.Attempt, error)) *mockAttemptBuilder_NewAgnosticBumpAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAttemptBuilder creates a new instance of mockAttemptBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAttemptBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAttemptBuilder {
	mock := &mockAttemptBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
