// Code generated by mockery v2.53.3. DO NOT EDIT.

package logpoller

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	query "github.com/smartcontractkit/chainlink-common/pkg/types/query"

	time "time"

	types "github.com/smartcontractkit/chainlink-evm/pkg/types"
)

// MockORM is an autogenerated mock type for the ORM type
type MockORM struct {
	mock.Mock
}

type MockORM_Expecter struct {
	mock *mock.Mock
}

func (_m *MockORM) EXPECT() *MockORM_Expecter {
	return &MockORM_Expecter{mock: &_m.Mock}
}

// DeleteBlocksBefore provides a mock function with given fields: ctx, end, limit
func (_m *MockORM) DeleteBlocksBefore(ctx context.Context, end int64, limit int64) (int64, error) {
	ret := _m.Called(ctx, end, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlocksBefore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return rf(ctx, end, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = rf(ctx, end, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, end, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_DeleteBlocksBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlocksBefore'
type MockORM_DeleteBlocksBefore_Call struct {
	*mock.Call
}

// DeleteBlocksBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - end int64
//   - limit int64
func (_e *MockORM_Expecter) DeleteBlocksBefore(ctx interface{}, end interface{}, limit interface{}) *MockORM_DeleteBlocksBefore_Call {
	return &MockORM_DeleteBlocksBefore_Call{Call: _e.mock.On("DeleteBlocksBefore", ctx, end, limit)}
}

func (_c *MockORM_DeleteBlocksBefore_Call) Run(run func(ctx context.Context, end int64, limit int64)) *MockORM_DeleteBlocksBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockORM_DeleteBlocksBefore_Call) Return(_a0 int64, _a1 error) *MockORM_DeleteBlocksBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_DeleteBlocksBefore_Call) RunAndReturn(run func(context.Context, int64, int64) (int64, error)) *MockORM_DeleteBlocksBefore_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredLogs provides a mock function with given fields: ctx, limit
func (_m *MockORM) DeleteExpiredLogs(ctx context.Context, limit int64) (int64, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredLogs")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_DeleteExpiredLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredLogs'
type MockORM_DeleteExpiredLogs_Call struct {
	*mock.Call
}

// DeleteExpiredLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockORM_Expecter) DeleteExpiredLogs(ctx interface{}, limit interface{}) *MockORM_DeleteExpiredLogs_Call {
	return &MockORM_DeleteExpiredLogs_Call{Call: _e.mock.On("DeleteExpiredLogs", ctx, limit)}
}

func (_c *MockORM_DeleteExpiredLogs_Call) Run(run func(ctx context.Context, limit int64)) *MockORM_DeleteExpiredLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockORM_DeleteExpiredLogs_Call) Return(_a0 int64, _a1 error) *MockORM_DeleteExpiredLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_DeleteExpiredLogs_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockORM_DeleteExpiredLogs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFilter provides a mock function with given fields: ctx, name
func (_m *MockORM) DeleteFilter(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFilter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockORM_DeleteFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFilter'
type MockORM_DeleteFilter_Call struct {
	*mock.Call
}

// DeleteFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockORM_Expecter) DeleteFilter(ctx interface{}, name interface{}) *MockORM_DeleteFilter_Call {
	return &MockORM_DeleteFilter_Call{Call: _e.mock.On("DeleteFilter", ctx, name)}
}

func (_c *MockORM_DeleteFilter_Call) Run(run func(ctx context.Context, name string)) *MockORM_DeleteFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockORM_DeleteFilter_Call) Return(_a0 error) *MockORM_DeleteFilter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockORM_DeleteFilter_Call) RunAndReturn(run func(context.Context, string) error) *MockORM_DeleteFilter_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLogsAndBlocksAfter provides a mock function with given fields: ctx, start
func (_m *MockORM) DeleteLogsAndBlocksAfter(ctx context.Context, start int64) error {
	ret := _m.Called(ctx, start)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLogsAndBlocksAfter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, start)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockORM_DeleteLogsAndBlocksAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLogsAndBlocksAfter'
type MockORM_DeleteLogsAndBlocksAfter_Call struct {
	*mock.Call
}

// DeleteLogsAndBlocksAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - start int64
func (_e *MockORM_Expecter) DeleteLogsAndBlocksAfter(ctx interface{}, start interface{}) *MockORM_DeleteLogsAndBlocksAfter_Call {
	return &MockORM_DeleteLogsAndBlocksAfter_Call{Call: _e.mock.On("DeleteLogsAndBlocksAfter", ctx, start)}
}

func (_c *MockORM_DeleteLogsAndBlocksAfter_Call) Run(run func(ctx context.Context, start int64)) *MockORM_DeleteLogsAndBlocksAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockORM_DeleteLogsAndBlocksAfter_Call) Return(_a0 error) *MockORM_DeleteLogsAndBlocksAfter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockORM_DeleteLogsAndBlocksAfter_Call) RunAndReturn(run func(context.Context, int64) error) *MockORM_DeleteLogsAndBlocksAfter_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLogsByRowID provides a mock function with given fields: ctx, rowIDs
func (_m *MockORM) DeleteLogsByRowID(ctx context.Context, rowIDs []uint64) (int64, error) {
	ret := _m.Called(ctx, rowIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLogsByRowID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) (int64, error)); ok {
		return rf(ctx, rowIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) int64); ok {
		r0 = rf(ctx, rowIDs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, rowIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_DeleteLogsByRowID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLogsByRowID'
type MockORM_DeleteLogsByRowID_Call struct {
	*mock.Call
}

// DeleteLogsByRowID is a helper method to define mock.On call
//   - ctx context.Context
//   - rowIDs []uint64
func (_e *MockORM_Expecter) DeleteLogsByRowID(ctx interface{}, rowIDs interface{}) *MockORM_DeleteLogsByRowID_Call {
	return &MockORM_DeleteLogsByRowID_Call{Call: _e.mock.On("DeleteLogsByRowID", ctx, rowIDs)}
}

func (_c *MockORM_DeleteLogsByRowID_Call) Run(run func(ctx context.Context, rowIDs []uint64)) *MockORM_DeleteLogsByRowID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *MockORM_DeleteLogsByRowID_Call) Return(_a0 int64, _a1 error) *MockORM_DeleteLogsByRowID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_DeleteLogsByRowID_Call) RunAndReturn(run func(context.Context, []uint64) (int64, error)) *MockORM_DeleteLogsByRowID_Call {
	_c.Call.Return(run)
	return _c
}

// FilteredLogs provides a mock function with given fields: ctx, filter, limitAndSort, queryName
func (_m *MockORM) FilteredLogs(ctx context.Context, filter []query.Expression, limitAndSort query.LimitAndSort, queryName string) ([]Log, error) {
	ret := _m.Called(ctx, filter, limitAndSort, queryName)

	if len(ret) == 0 {
		panic("no return value specified for FilteredLogs")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []query.Expression, query.LimitAndSort, string) ([]Log, error)); ok {
		return rf(ctx, filter, limitAndSort, queryName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []query.Expression, query.LimitAndSort, string) []Log); ok {
		r0 = rf(ctx, filter, limitAndSort, queryName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []query.Expression, query.LimitAndSort, string) error); ok {
		r1 = rf(ctx, filter, limitAndSort, queryName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_FilteredLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilteredLogs'
type MockORM_FilteredLogs_Call struct {
	*mock.Call
}

// FilteredLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - filter []query.Expression
//   - limitAndSort query.LimitAndSort
//   - queryName string
func (_e *MockORM_Expecter) FilteredLogs(ctx interface{}, filter interface{}, limitAndSort interface{}, queryName interface{}) *MockORM_FilteredLogs_Call {
	return &MockORM_FilteredLogs_Call{Call: _e.mock.On("FilteredLogs", ctx, filter, limitAndSort, queryName)}
}

func (_c *MockORM_FilteredLogs_Call) Run(run func(ctx context.Context, filter []query.Expression, limitAndSort query.LimitAndSort, queryName string)) *MockORM_FilteredLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]query.Expression), args[2].(query.LimitAndSort), args[3].(string))
	})
	return _c
}

func (_c *MockORM_FilteredLogs_Call) Return(_a0 []Log, _a1 error) *MockORM_FilteredLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_FilteredLogs_Call) RunAndReturn(run func(context.Context, []query.Expression, query.LimitAndSort, string) ([]Log, error)) *MockORM_FilteredLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocksRange provides a mock function with given fields: ctx, start, end
func (_m *MockORM) GetBlocksRange(ctx context.Context, start int64, end int64) ([]Block, error) {
	ret := _m.Called(ctx, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocksRange")
	}

	var r0 []Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]Block, error)); ok {
		return rf(ctx, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []Block); ok {
		r0 = rf(ctx, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_GetBlocksRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocksRange'
type MockORM_GetBlocksRange_Call struct {
	*mock.Call
}

// GetBlocksRange is a helper method to define mock.On call
//   - ctx context.Context
//   - start int64
//   - end int64
func (_e *MockORM_Expecter) GetBlocksRange(ctx interface{}, start interface{}, end interface{}) *MockORM_GetBlocksRange_Call {
	return &MockORM_GetBlocksRange_Call{Call: _e.mock.On("GetBlocksRange", ctx, start, end)}
}

func (_c *MockORM_GetBlocksRange_Call) Run(run func(ctx context.Context, start int64, end int64)) *MockORM_GetBlocksRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockORM_GetBlocksRange_Call) Return(_a0 []Block, _a1 error) *MockORM_GetBlocksRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_GetBlocksRange_Call) RunAndReturn(run func(context.Context, int64, int64) ([]Block, error)) *MockORM_GetBlocksRange_Call {
	_c.Call.Return(run)
	return _c
}

// InsertBlock provides a mock function with given fields: ctx, blockHash, blockNumber, blockTimestamp, finalizedBlock, safeBlock
func (_m *MockORM) InsertBlock(ctx context.Context, blockHash common.Hash, blockNumber int64, blockTimestamp time.Time, finalizedBlock int64, safeBlock int64) error {
	ret := _m.Called(ctx, blockHash, blockNumber, blockTimestamp, finalizedBlock, safeBlock)

	if len(ret) == 0 {
		panic("no return value specified for InsertBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, int64, time.Time, int64, int64) error); ok {
		r0 = rf(ctx, blockHash, blockNumber, blockTimestamp, finalizedBlock, safeBlock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockORM_InsertBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBlock'
type MockORM_InsertBlock_Call struct {
	*mock.Call
}

// InsertBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - blockHash common.Hash
//   - blockNumber int64
//   - blockTimestamp time.Time
//   - finalizedBlock int64
//   - safeBlock int64
func (_e *MockORM_Expecter) InsertBlock(ctx interface{}, blockHash interface{}, blockNumber interface{}, blockTimestamp interface{}, finalizedBlock interface{}, safeBlock interface{}) *MockORM_InsertBlock_Call {
	return &MockORM_InsertBlock_Call{Call: _e.mock.On("InsertBlock", ctx, blockHash, blockNumber, blockTimestamp, finalizedBlock, safeBlock)}
}

func (_c *MockORM_InsertBlock_Call) Run(run func(ctx context.Context, blockHash common.Hash, blockNumber int64, blockTimestamp time.Time, finalizedBlock int64, safeBlock int64)) *MockORM_InsertBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash), args[2].(int64), args[3].(time.Time), args[4].(int64), args[5].(int64))
	})
	return _c
}

func (_c *MockORM_InsertBlock_Call) Return(_a0 error) *MockORM_InsertBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockORM_InsertBlock_Call) RunAndReturn(run func(context.Context, common.Hash, int64, time.Time, int64, int64) error) *MockORM_InsertBlock_Call {
	_c.Call.Return(run)
	return _c
}

// InsertFilter provides a mock function with given fields: ctx, filter
func (_m *MockORM) InsertFilter(ctx context.Context, filter Filter) error {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for InsertFilter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Filter) error); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockORM_InsertFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFilter'
type MockORM_InsertFilter_Call struct {
	*mock.Call
}

// InsertFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter Filter
func (_e *MockORM_Expecter) InsertFilter(ctx interface{}, filter interface{}) *MockORM_InsertFilter_Call {
	return &MockORM_InsertFilter_Call{Call: _e.mock.On("InsertFilter", ctx, filter)}
}

func (_c *MockORM_InsertFilter_Call) Run(run func(ctx context.Context, filter Filter)) *MockORM_InsertFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Filter))
	})
	return _c
}

func (_c *MockORM_InsertFilter_Call) Return(_a0 error) *MockORM_InsertFilter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockORM_InsertFilter_Call) RunAndReturn(run func(context.Context, Filter) error) *MockORM_InsertFilter_Call {
	_c.Call.Return(run)
	return _c
}

// InsertLogs provides a mock function with given fields: ctx, logs
func (_m *MockORM) InsertLogs(ctx context.Context, logs []Log) error {
	ret := _m.Called(ctx, logs)

	if len(ret) == 0 {
		panic("no return value specified for InsertLogs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []Log) error); ok {
		r0 = rf(ctx, logs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockORM_InsertLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLogs'
type MockORM_InsertLogs_Call struct {
	*mock.Call
}

// InsertLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - logs []Log
func (_e *MockORM_Expecter) InsertLogs(ctx interface{}, logs interface{}) *MockORM_InsertLogs_Call {
	return &MockORM_InsertLogs_Call{Call: _e.mock.On("InsertLogs", ctx, logs)}
}

func (_c *MockORM_InsertLogs_Call) Run(run func(ctx context.Context, logs []Log)) *MockORM_InsertLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]Log))
	})
	return _c
}

func (_c *MockORM_InsertLogs_Call) Return(_a0 error) *MockORM_InsertLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockORM_InsertLogs_Call) RunAndReturn(run func(context.Context, []Log) error) *MockORM_InsertLogs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertLogsWithBlocks provides a mock function with given fields: ctx, logs, blocks
func (_m *MockORM) InsertLogsWithBlocks(ctx context.Context, logs []Log, blocks []Block) error {
	ret := _m.Called(ctx, logs, blocks)

	if len(ret) == 0 {
		panic("no return value specified for InsertLogsWithBlocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []Log, []Block) error); ok {
		r0 = rf(ctx, logs, blocks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockORM_InsertLogsWithBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLogsWithBlocks'
type MockORM_InsertLogsWithBlocks_Call struct {
	*mock.Call
}

// InsertLogsWithBlocks is a helper method to define mock.On call
//   - ctx context.Context
//   - logs []Log
//   - blocks []Block
func (_e *MockORM_Expecter) InsertLogsWithBlocks(ctx interface{}, logs interface{}, blocks interface{}) *MockORM_InsertLogsWithBlocks_Call {
	return &MockORM_InsertLogsWithBlocks_Call{Call: _e.mock.On("InsertLogsWithBlocks", ctx, logs, blocks)}
}

func (_c *MockORM_InsertLogsWithBlocks_Call) Run(run func(ctx context.Context, logs []Log, blocks []Block)) *MockORM_InsertLogsWithBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]Log), args[2].([]Block))
	})
	return _c
}

func (_c *MockORM_InsertLogsWithBlocks_Call) Return(_a0 error) *MockORM_InsertLogsWithBlocks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockORM_InsertLogsWithBlocks_Call) RunAndReturn(run func(context.Context, []Log, []Block) error) *MockORM_InsertLogsWithBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// LoadFilters provides a mock function with given fields: ctx
func (_m *MockORM) LoadFilters(ctx context.Context) (map[string]Filter, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadFilters")
	}

	var r0 map[string]Filter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]Filter, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]Filter); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]Filter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_LoadFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadFilters'
type MockORM_LoadFilters_Call struct {
	*mock.Call
}

// LoadFilters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockORM_Expecter) LoadFilters(ctx interface{}) *MockORM_LoadFilters_Call {
	return &MockORM_LoadFilters_Call{Call: _e.mock.On("LoadFilters", ctx)}
}

func (_c *MockORM_LoadFilters_Call) Run(run func(ctx context.Context)) *MockORM_LoadFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockORM_LoadFilters_Call) Return(_a0 map[string]Filter, _a1 error) *MockORM_LoadFilters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_LoadFilters_Call) RunAndReturn(run func(context.Context) (map[string]Filter, error)) *MockORM_LoadFilters_Call {
	_c.Call.Return(run)
	return _c
}

// SelectBlockByHash provides a mock function with given fields: ctx, hash
func (_m *MockORM) SelectBlockByHash(ctx context.Context, hash common.Hash) (*Block, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for SelectBlockByHash")
	}

	var r0 *Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) (*Block, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) *Block); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectBlockByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectBlockByHash'
type MockORM_SelectBlockByHash_Call struct {
	*mock.Call
}

// SelectBlockByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash common.Hash
func (_e *MockORM_Expecter) SelectBlockByHash(ctx interface{}, hash interface{}) *MockORM_SelectBlockByHash_Call {
	return &MockORM_SelectBlockByHash_Call{Call: _e.mock.On("SelectBlockByHash", ctx, hash)}
}

func (_c *MockORM_SelectBlockByHash_Call) Run(run func(ctx context.Context, hash common.Hash)) *MockORM_SelectBlockByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash))
	})
	return _c
}

func (_c *MockORM_SelectBlockByHash_Call) Return(_a0 *Block, _a1 error) *MockORM_SelectBlockByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectBlockByHash_Call) RunAndReturn(run func(context.Context, common.Hash) (*Block, error)) *MockORM_SelectBlockByHash_Call {
	_c.Call.Return(run)
	return _c
}

// SelectBlockByNumber provides a mock function with given fields: ctx, blockNumber
func (_m *MockORM) SelectBlockByNumber(ctx context.Context, blockNumber int64) (*Block, error) {
	ret := _m.Called(ctx, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for SelectBlockByNumber")
	}

	var r0 *Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*Block, error)); ok {
		return rf(ctx, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *Block); ok {
		r0 = rf(ctx, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectBlockByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectBlockByNumber'
type MockORM_SelectBlockByNumber_Call struct {
	*mock.Call
}

// SelectBlockByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber int64
func (_e *MockORM_Expecter) SelectBlockByNumber(ctx interface{}, blockNumber interface{}) *MockORM_SelectBlockByNumber_Call {
	return &MockORM_SelectBlockByNumber_Call{Call: _e.mock.On("SelectBlockByNumber", ctx, blockNumber)}
}

func (_c *MockORM_SelectBlockByNumber_Call) Run(run func(ctx context.Context, blockNumber int64)) *MockORM_SelectBlockByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockORM_SelectBlockByNumber_Call) Return(_a0 *Block, _a1 error) *MockORM_SelectBlockByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectBlockByNumber_Call) RunAndReturn(run func(context.Context, int64) (*Block, error)) *MockORM_SelectBlockByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// SelectExcessLogIDs provides a mock function with given fields: ctx, limit
func (_m *MockORM) SelectExcessLogIDs(ctx context.Context, limit int64) ([]uint64, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for SelectExcessLogIDs")
	}

	var r0 []uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]uint64, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []uint64); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectExcessLogIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectExcessLogIDs'
type MockORM_SelectExcessLogIDs_Call struct {
	*mock.Call
}

// SelectExcessLogIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockORM_Expecter) SelectExcessLogIDs(ctx interface{}, limit interface{}) *MockORM_SelectExcessLogIDs_Call {
	return &MockORM_SelectExcessLogIDs_Call{Call: _e.mock.On("SelectExcessLogIDs", ctx, limit)}
}

func (_c *MockORM_SelectExcessLogIDs_Call) Run(run func(ctx context.Context, limit int64)) *MockORM_SelectExcessLogIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockORM_SelectExcessLogIDs_Call) Return(rowIDs []uint64, err error) *MockORM_SelectExcessLogIDs_Call {
	_c.Call.Return(rowIDs, err)
	return _c
}

func (_c *MockORM_SelectExcessLogIDs_Call) RunAndReturn(run func(context.Context, int64) ([]uint64, error)) *MockORM_SelectExcessLogIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SelectIndexedLogs provides a mock function with given fields: ctx, address, eventSig, topicIndex, topicValues, confs
func (_m *MockORM) SelectIndexedLogs(ctx context.Context, address common.Address, eventSig common.Hash, topicIndex int, topicValues []common.Hash, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, topicIndex, topicValues, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectIndexedLogs")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, []common.Hash, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, topicIndex, topicValues, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, []common.Hash, types.Confirmations) []Log); ok {
		r0 = rf(ctx, address, eventSig, topicIndex, topicValues, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, int, []common.Hash, types.Confirmations) error); ok {
		r1 = rf(ctx, address, eventSig, topicIndex, topicValues, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectIndexedLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectIndexedLogs'
type MockORM_SelectIndexedLogs_Call struct {
	*mock.Call
}

// SelectIndexedLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - topicIndex int
//   - topicValues []common.Hash
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectIndexedLogs(ctx interface{}, address interface{}, eventSig interface{}, topicIndex interface{}, topicValues interface{}, confs interface{}) *MockORM_SelectIndexedLogs_Call {
	return &MockORM_SelectIndexedLogs_Call{Call: _e.mock.On("SelectIndexedLogs", ctx, address, eventSig, topicIndex, topicValues, confs)}
}

func (_c *MockORM_SelectIndexedLogs_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, topicIndex int, topicValues []common.Hash, confs types.Confirmations)) *MockORM_SelectIndexedLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(int), args[4].([]common.Hash), args[5].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectIndexedLogs_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectIndexedLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectIndexedLogs_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, int, []common.Hash, types.Confirmations) ([]Log, error)) *MockORM_SelectIndexedLogs_Call {
	_c.Call.Return(run)
	return _c
}

// SelectIndexedLogsByBlockRange provides a mock function with given fields: ctx, start, end, address, eventSig, topicIndex, topicValues
func (_m *MockORM) SelectIndexedLogsByBlockRange(ctx context.Context, start int64, end int64, address common.Address, eventSig common.Hash, topicIndex int, topicValues []common.Hash) ([]Log, error) {
	ret := _m.Called(ctx, start, end, address, eventSig, topicIndex, topicValues)

	if len(ret) == 0 {
		panic("no return value specified for SelectIndexedLogsByBlockRange")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, common.Address, common.Hash, int, []common.Hash) ([]Log, error)); ok {
		return rf(ctx, start, end, address, eventSig, topicIndex, topicValues)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, common.Address, common.Hash, int, []common.Hash) []Log); ok {
		r0 = rf(ctx, start, end, address, eventSig, topicIndex, topicValues)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, common.Address, common.Hash, int, []common.Hash) error); ok {
		r1 = rf(ctx, start, end, address, eventSig, topicIndex, topicValues)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectIndexedLogsByBlockRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectIndexedLogsByBlockRange'
type MockORM_SelectIndexedLogsByBlockRange_Call struct {
	*mock.Call
}

// SelectIndexedLogsByBlockRange is a helper method to define mock.On call
//   - ctx context.Context
//   - start int64
//   - end int64
//   - address common.Address
//   - eventSig common.Hash
//   - topicIndex int
//   - topicValues []common.Hash
func (_e *MockORM_Expecter) SelectIndexedLogsByBlockRange(ctx interface{}, start interface{}, end interface{}, address interface{}, eventSig interface{}, topicIndex interface{}, topicValues interface{}) *MockORM_SelectIndexedLogsByBlockRange_Call {
	return &MockORM_SelectIndexedLogsByBlockRange_Call{Call: _e.mock.On("SelectIndexedLogsByBlockRange", ctx, start, end, address, eventSig, topicIndex, topicValues)}
}

func (_c *MockORM_SelectIndexedLogsByBlockRange_Call) Run(run func(ctx context.Context, start int64, end int64, address common.Address, eventSig common.Hash, topicIndex int, topicValues []common.Hash)) *MockORM_SelectIndexedLogsByBlockRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(common.Address), args[4].(common.Hash), args[5].(int), args[6].([]common.Hash))
	})
	return _c
}

func (_c *MockORM_SelectIndexedLogsByBlockRange_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectIndexedLogsByBlockRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectIndexedLogsByBlockRange_Call) RunAndReturn(run func(context.Context, int64, int64, common.Address, common.Hash, int, []common.Hash) ([]Log, error)) *MockORM_SelectIndexedLogsByBlockRange_Call {
	_c.Call.Return(run)
	return _c
}

// SelectIndexedLogsByTxHash provides a mock function with given fields: ctx, address, eventSig, txHash
func (_m *MockORM) SelectIndexedLogsByTxHash(ctx context.Context, address common.Address, eventSig common.Hash, txHash common.Hash) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, txHash)

	if len(ret) == 0 {
		panic("no return value specified for SelectIndexedLogsByTxHash")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, common.Hash) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, txHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, common.Hash) []Log); ok {
		r0 = rf(ctx, address, eventSig, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, common.Hash) error); ok {
		r1 = rf(ctx, address, eventSig, txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectIndexedLogsByTxHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectIndexedLogsByTxHash'
type MockORM_SelectIndexedLogsByTxHash_Call struct {
	*mock.Call
}

// SelectIndexedLogsByTxHash is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - txHash common.Hash
func (_e *MockORM_Expecter) SelectIndexedLogsByTxHash(ctx interface{}, address interface{}, eventSig interface{}, txHash interface{}) *MockORM_SelectIndexedLogsByTxHash_Call {
	return &MockORM_SelectIndexedLogsByTxHash_Call{Call: _e.mock.On("SelectIndexedLogsByTxHash", ctx, address, eventSig, txHash)}
}

func (_c *MockORM_SelectIndexedLogsByTxHash_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, txHash common.Hash)) *MockORM_SelectIndexedLogsByTxHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(common.Hash))
	})
	return _c
}

func (_c *MockORM_SelectIndexedLogsByTxHash_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectIndexedLogsByTxHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectIndexedLogsByTxHash_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, common.Hash) ([]Log, error)) *MockORM_SelectIndexedLogsByTxHash_Call {
	_c.Call.Return(run)
	return _c
}

// SelectIndexedLogsCreatedAfter provides a mock function with given fields: ctx, address, eventSig, topicIndex, topicValues, after, confs
func (_m *MockORM) SelectIndexedLogsCreatedAfter(ctx context.Context, address common.Address, eventSig common.Hash, topicIndex int, topicValues []common.Hash, after time.Time, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, topicIndex, topicValues, after, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectIndexedLogsCreatedAfter")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, []common.Hash, time.Time, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, topicIndex, topicValues, after, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, []common.Hash, time.Time, types.Confirmations) []Log); ok {
		r0 = rf(ctx, address, eventSig, topicIndex, topicValues, after, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, int, []common.Hash, time.Time, types.Confirmations) error); ok {
		r1 = rf(ctx, address, eventSig, topicIndex, topicValues, after, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectIndexedLogsCreatedAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectIndexedLogsCreatedAfter'
type MockORM_SelectIndexedLogsCreatedAfter_Call struct {
	*mock.Call
}

// SelectIndexedLogsCreatedAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - topicIndex int
//   - topicValues []common.Hash
//   - after time.Time
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectIndexedLogsCreatedAfter(ctx interface{}, address interface{}, eventSig interface{}, topicIndex interface{}, topicValues interface{}, after interface{}, confs interface{}) *MockORM_SelectIndexedLogsCreatedAfter_Call {
	return &MockORM_SelectIndexedLogsCreatedAfter_Call{Call: _e.mock.On("SelectIndexedLogsCreatedAfter", ctx, address, eventSig, topicIndex, topicValues, after, confs)}
}

func (_c *MockORM_SelectIndexedLogsCreatedAfter_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, topicIndex int, topicValues []common.Hash, after time.Time, confs types.Confirmations)) *MockORM_SelectIndexedLogsCreatedAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(int), args[4].([]common.Hash), args[5].(time.Time), args[6].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectIndexedLogsCreatedAfter_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectIndexedLogsCreatedAfter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectIndexedLogsCreatedAfter_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, int, []common.Hash, time.Time, types.Confirmations) ([]Log, error)) *MockORM_SelectIndexedLogsCreatedAfter_Call {
	_c.Call.Return(run)
	return _c
}

// SelectIndexedLogsTopicGreaterThan provides a mock function with given fields: ctx, address, eventSig, topicIndex, topicValueMin, confs
func (_m *MockORM) SelectIndexedLogsTopicGreaterThan(ctx context.Context, address common.Address, eventSig common.Hash, topicIndex int, topicValueMin common.Hash, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, topicIndex, topicValueMin, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectIndexedLogsTopicGreaterThan")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, common.Hash, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, topicIndex, topicValueMin, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, common.Hash, types.Confirmations) []Log); ok {
		r0 = rf(ctx, address, eventSig, topicIndex, topicValueMin, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, int, common.Hash, types.Confirmations) error); ok {
		r1 = rf(ctx, address, eventSig, topicIndex, topicValueMin, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectIndexedLogsTopicGreaterThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectIndexedLogsTopicGreaterThan'
type MockORM_SelectIndexedLogsTopicGreaterThan_Call struct {
	*mock.Call
}

// SelectIndexedLogsTopicGreaterThan is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - topicIndex int
//   - topicValueMin common.Hash
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectIndexedLogsTopicGreaterThan(ctx interface{}, address interface{}, eventSig interface{}, topicIndex interface{}, topicValueMin interface{}, confs interface{}) *MockORM_SelectIndexedLogsTopicGreaterThan_Call {
	return &MockORM_SelectIndexedLogsTopicGreaterThan_Call{Call: _e.mock.On("SelectIndexedLogsTopicGreaterThan", ctx, address, eventSig, topicIndex, topicValueMin, confs)}
}

func (_c *MockORM_SelectIndexedLogsTopicGreaterThan_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, topicIndex int, topicValueMin common.Hash, confs types.Confirmations)) *MockORM_SelectIndexedLogsTopicGreaterThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(int), args[4].(common.Hash), args[5].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectIndexedLogsTopicGreaterThan_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectIndexedLogsTopicGreaterThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectIndexedLogsTopicGreaterThan_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, int, common.Hash, types.Confirmations) ([]Log, error)) *MockORM_SelectIndexedLogsTopicGreaterThan_Call {
	_c.Call.Return(run)
	return _c
}

// SelectIndexedLogsTopicRange provides a mock function with given fields: ctx, address, eventSig, topicIndex, topicValueMin, topicValueMax, confs
func (_m *MockORM) SelectIndexedLogsTopicRange(ctx context.Context, address common.Address, eventSig common.Hash, topicIndex int, topicValueMin common.Hash, topicValueMax common.Hash, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, topicIndex, topicValueMin, topicValueMax, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectIndexedLogsTopicRange")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, common.Hash, common.Hash, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, topicIndex, topicValueMin, topicValueMax, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, common.Hash, common.Hash, types.Confirmations) []Log); ok {
		r0 = rf(ctx, address, eventSig, topicIndex, topicValueMin, topicValueMax, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, int, common.Hash, common.Hash, types.Confirmations) error); ok {
		r1 = rf(ctx, address, eventSig, topicIndex, topicValueMin, topicValueMax, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectIndexedLogsTopicRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectIndexedLogsTopicRange'
type MockORM_SelectIndexedLogsTopicRange_Call struct {
	*mock.Call
}

// SelectIndexedLogsTopicRange is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - topicIndex int
//   - topicValueMin common.Hash
//   - topicValueMax common.Hash
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectIndexedLogsTopicRange(ctx interface{}, address interface{}, eventSig interface{}, topicIndex interface{}, topicValueMin interface{}, topicValueMax interface{}, confs interface{}) *MockORM_SelectIndexedLogsTopicRange_Call {
	return &MockORM_SelectIndexedLogsTopicRange_Call{Call: _e.mock.On("SelectIndexedLogsTopicRange", ctx, address, eventSig, topicIndex, topicValueMin, topicValueMax, confs)}
}

func (_c *MockORM_SelectIndexedLogsTopicRange_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, topicIndex int, topicValueMin common.Hash, topicValueMax common.Hash, confs types.Confirmations)) *MockORM_SelectIndexedLogsTopicRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(int), args[4].(common.Hash), args[5].(common.Hash), args[6].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectIndexedLogsTopicRange_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectIndexedLogsTopicRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectIndexedLogsTopicRange_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, int, common.Hash, common.Hash, types.Confirmations) ([]Log, error)) *MockORM_SelectIndexedLogsTopicRange_Call {
	_c.Call.Return(run)
	return _c
}

// SelectIndexedLogsWithSigsExcluding provides a mock function with given fields: ctx, sigA, sigB, topicIndex, address, startBlock, endBlock, confs
func (_m *MockORM) SelectIndexedLogsWithSigsExcluding(ctx context.Context, sigA common.Hash, sigB common.Hash, topicIndex int, address common.Address, startBlock int64, endBlock int64, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, sigA, sigB, topicIndex, address, startBlock, endBlock, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectIndexedLogsWithSigsExcluding")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, common.Hash, int, common.Address, int64, int64, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, sigA, sigB, topicIndex, address, startBlock, endBlock, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, common.Hash, int, common.Address, int64, int64, types.Confirmations) []Log); ok {
		r0 = rf(ctx, sigA, sigB, topicIndex, address, startBlock, endBlock, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash, common.Hash, int, common.Address, int64, int64, types.Confirmations) error); ok {
		r1 = rf(ctx, sigA, sigB, topicIndex, address, startBlock, endBlock, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectIndexedLogsWithSigsExcluding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectIndexedLogsWithSigsExcluding'
type MockORM_SelectIndexedLogsWithSigsExcluding_Call struct {
	*mock.Call
}

// SelectIndexedLogsWithSigsExcluding is a helper method to define mock.On call
//   - ctx context.Context
//   - sigA common.Hash
//   - sigB common.Hash
//   - topicIndex int
//   - address common.Address
//   - startBlock int64
//   - endBlock int64
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectIndexedLogsWithSigsExcluding(ctx interface{}, sigA interface{}, sigB interface{}, topicIndex interface{}, address interface{}, startBlock interface{}, endBlock interface{}, confs interface{}) *MockORM_SelectIndexedLogsWithSigsExcluding_Call {
	return &MockORM_SelectIndexedLogsWithSigsExcluding_Call{Call: _e.mock.On("SelectIndexedLogsWithSigsExcluding", ctx, sigA, sigB, topicIndex, address, startBlock, endBlock, confs)}
}

func (_c *MockORM_SelectIndexedLogsWithSigsExcluding_Call) Run(run func(ctx context.Context, sigA common.Hash, sigB common.Hash, topicIndex int, address common.Address, startBlock int64, endBlock int64, confs types.Confirmations)) *MockORM_SelectIndexedLogsWithSigsExcluding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash), args[2].(common.Hash), args[3].(int), args[4].(common.Address), args[5].(int64), args[6].(int64), args[7].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectIndexedLogsWithSigsExcluding_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectIndexedLogsWithSigsExcluding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectIndexedLogsWithSigsExcluding_Call) RunAndReturn(run func(context.Context, common.Hash, common.Hash, int, common.Address, int64, int64, types.Confirmations) ([]Log, error)) *MockORM_SelectIndexedLogsWithSigsExcluding_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLatestBlock provides a mock function with given fields: ctx
func (_m *MockORM) SelectLatestBlock(ctx context.Context) (*Block, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SelectLatestBlock")
	}

	var r0 *Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*Block, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *Block); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLatestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLatestBlock'
type MockORM_SelectLatestBlock_Call struct {
	*mock.Call
}

// SelectLatestBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockORM_Expecter) SelectLatestBlock(ctx interface{}) *MockORM_SelectLatestBlock_Call {
	return &MockORM_SelectLatestBlock_Call{Call: _e.mock.On("SelectLatestBlock", ctx)}
}

func (_c *MockORM_SelectLatestBlock_Call) Run(run func(ctx context.Context)) *MockORM_SelectLatestBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockORM_SelectLatestBlock_Call) Return(_a0 *Block, _a1 error) *MockORM_SelectLatestBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLatestBlock_Call) RunAndReturn(run func(context.Context) (*Block, error)) *MockORM_SelectLatestBlock_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLatestBlockByEventSigsAddrsWithConfs provides a mock function with given fields: ctx, fromBlock, eventSigs, addresses, confs
func (_m *MockORM) SelectLatestBlockByEventSigsAddrsWithConfs(ctx context.Context, fromBlock int64, eventSigs []common.Hash, addresses []common.Address, confs types.Confirmations) (int64, error) {
	ret := _m.Called(ctx, fromBlock, eventSigs, addresses, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectLatestBlockByEventSigsAddrsWithConfs")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []common.Hash, []common.Address, types.Confirmations) (int64, error)); ok {
		return rf(ctx, fromBlock, eventSigs, addresses, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []common.Hash, []common.Address, types.Confirmations) int64); ok {
		r0 = rf(ctx, fromBlock, eventSigs, addresses, confs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []common.Hash, []common.Address, types.Confirmations) error); ok {
		r1 = rf(ctx, fromBlock, eventSigs, addresses, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLatestBlockByEventSigsAddrsWithConfs'
type MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call struct {
	*mock.Call
}

// SelectLatestBlockByEventSigsAddrsWithConfs is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock int64
//   - eventSigs []common.Hash
//   - addresses []common.Address
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectLatestBlockByEventSigsAddrsWithConfs(ctx interface{}, fromBlock interface{}, eventSigs interface{}, addresses interface{}, confs interface{}) *MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call {
	return &MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call{Call: _e.mock.On("SelectLatestBlockByEventSigsAddrsWithConfs", ctx, fromBlock, eventSigs, addresses, confs)}
}

func (_c *MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call) Run(run func(ctx context.Context, fromBlock int64, eventSigs []common.Hash, addresses []common.Address, confs types.Confirmations)) *MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]common.Hash), args[3].([]common.Address), args[4].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call) Return(_a0 int64, _a1 error) *MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call) RunAndReturn(run func(context.Context, int64, []common.Hash, []common.Address, types.Confirmations) (int64, error)) *MockORM_SelectLatestBlockByEventSigsAddrsWithConfs_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLatestFinalizedBlock provides a mock function with given fields: ctx
func (_m *MockORM) SelectLatestFinalizedBlock(ctx context.Context) (*Block, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SelectLatestFinalizedBlock")
	}

	var r0 *Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*Block, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *Block); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLatestFinalizedBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLatestFinalizedBlock'
type MockORM_SelectLatestFinalizedBlock_Call struct {
	*mock.Call
}

// SelectLatestFinalizedBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockORM_Expecter) SelectLatestFinalizedBlock(ctx interface{}) *MockORM_SelectLatestFinalizedBlock_Call {
	return &MockORM_SelectLatestFinalizedBlock_Call{Call: _e.mock.On("SelectLatestFinalizedBlock", ctx)}
}

func (_c *MockORM_SelectLatestFinalizedBlock_Call) Run(run func(ctx context.Context)) *MockORM_SelectLatestFinalizedBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockORM_SelectLatestFinalizedBlock_Call) Return(_a0 *Block, _a1 error) *MockORM_SelectLatestFinalizedBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLatestFinalizedBlock_Call) RunAndReturn(run func(context.Context) (*Block, error)) *MockORM_SelectLatestFinalizedBlock_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLatestLogByEventSigWithConfs provides a mock function with given fields: ctx, eventSig, address, confs
func (_m *MockORM) SelectLatestLogByEventSigWithConfs(ctx context.Context, eventSig common.Hash, address common.Address, confs types.Confirmations) (*Log, error) {
	ret := _m.Called(ctx, eventSig, address, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectLatestLogByEventSigWithConfs")
	}

	var r0 *Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, common.Address, types.Confirmations) (*Log, error)); ok {
		return rf(ctx, eventSig, address, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, common.Address, types.Confirmations) *Log); ok {
		r0 = rf(ctx, eventSig, address, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash, common.Address, types.Confirmations) error); ok {
		r1 = rf(ctx, eventSig, address, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLatestLogByEventSigWithConfs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLatestLogByEventSigWithConfs'
type MockORM_SelectLatestLogByEventSigWithConfs_Call struct {
	*mock.Call
}

// SelectLatestLogByEventSigWithConfs is a helper method to define mock.On call
//   - ctx context.Context
//   - eventSig common.Hash
//   - address common.Address
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectLatestLogByEventSigWithConfs(ctx interface{}, eventSig interface{}, address interface{}, confs interface{}) *MockORM_SelectLatestLogByEventSigWithConfs_Call {
	return &MockORM_SelectLatestLogByEventSigWithConfs_Call{Call: _e.mock.On("SelectLatestLogByEventSigWithConfs", ctx, eventSig, address, confs)}
}

func (_c *MockORM_SelectLatestLogByEventSigWithConfs_Call) Run(run func(ctx context.Context, eventSig common.Hash, address common.Address, confs types.Confirmations)) *MockORM_SelectLatestLogByEventSigWithConfs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash), args[2].(common.Address), args[3].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectLatestLogByEventSigWithConfs_Call) Return(_a0 *Log, _a1 error) *MockORM_SelectLatestLogByEventSigWithConfs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLatestLogByEventSigWithConfs_Call) RunAndReturn(run func(context.Context, common.Hash, common.Address, types.Confirmations) (*Log, error)) *MockORM_SelectLatestLogByEventSigWithConfs_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLatestLogEventSigsAddrsWithConfs provides a mock function with given fields: ctx, fromBlock, addresses, eventSigs, confs
func (_m *MockORM) SelectLatestLogEventSigsAddrsWithConfs(ctx context.Context, fromBlock int64, addresses []common.Address, eventSigs []common.Hash, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, fromBlock, addresses, eventSigs, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectLatestLogEventSigsAddrsWithConfs")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []common.Address, []common.Hash, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, fromBlock, addresses, eventSigs, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []common.Address, []common.Hash, types.Confirmations) []Log); ok {
		r0 = rf(ctx, fromBlock, addresses, eventSigs, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []common.Address, []common.Hash, types.Confirmations) error); ok {
		r1 = rf(ctx, fromBlock, addresses, eventSigs, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLatestLogEventSigsAddrsWithConfs'
type MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call struct {
	*mock.Call
}

// SelectLatestLogEventSigsAddrsWithConfs is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock int64
//   - addresses []common.Address
//   - eventSigs []common.Hash
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectLatestLogEventSigsAddrsWithConfs(ctx interface{}, fromBlock interface{}, addresses interface{}, eventSigs interface{}, confs interface{}) *MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call {
	return &MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call{Call: _e.mock.On("SelectLatestLogEventSigsAddrsWithConfs", ctx, fromBlock, addresses, eventSigs, confs)}
}

func (_c *MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call) Run(run func(ctx context.Context, fromBlock int64, addresses []common.Address, eventSigs []common.Hash, confs types.Confirmations)) *MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]common.Address), args[3].([]common.Hash), args[4].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call) RunAndReturn(run func(context.Context, int64, []common.Address, []common.Hash, types.Confirmations) ([]Log, error)) *MockORM_SelectLatestLogEventSigsAddrsWithConfs_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLogs provides a mock function with given fields: ctx, start, end, address, eventSig
func (_m *MockORM) SelectLogs(ctx context.Context, start int64, end int64, address common.Address, eventSig common.Hash) ([]Log, error) {
	ret := _m.Called(ctx, start, end, address, eventSig)

	if len(ret) == 0 {
		panic("no return value specified for SelectLogs")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, common.Address, common.Hash) ([]Log, error)); ok {
		return rf(ctx, start, end, address, eventSig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, common.Address, common.Hash) []Log); ok {
		r0 = rf(ctx, start, end, address, eventSig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, common.Address, common.Hash) error); ok {
		r1 = rf(ctx, start, end, address, eventSig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLogs'
type MockORM_SelectLogs_Call struct {
	*mock.Call
}

// SelectLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - start int64
//   - end int64
//   - address common.Address
//   - eventSig common.Hash
func (_e *MockORM_Expecter) SelectLogs(ctx interface{}, start interface{}, end interface{}, address interface{}, eventSig interface{}) *MockORM_SelectLogs_Call {
	return &MockORM_SelectLogs_Call{Call: _e.mock.On("SelectLogs", ctx, start, end, address, eventSig)}
}

func (_c *MockORM_SelectLogs_Call) Run(run func(ctx context.Context, start int64, end int64, address common.Address, eventSig common.Hash)) *MockORM_SelectLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(common.Address), args[4].(common.Hash))
	})
	return _c
}

func (_c *MockORM_SelectLogs_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLogs_Call) RunAndReturn(run func(context.Context, int64, int64, common.Address, common.Hash) ([]Log, error)) *MockORM_SelectLogs_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLogsByBlockRange provides a mock function with given fields: ctx, start, end
func (_m *MockORM) SelectLogsByBlockRange(ctx context.Context, start int64, end int64) ([]Log, error) {
	ret := _m.Called(ctx, start, end)

	if len(ret) == 0 {
		panic("no return value specified for SelectLogsByBlockRange")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]Log, error)); ok {
		return rf(ctx, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []Log); ok {
		r0 = rf(ctx, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLogsByBlockRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLogsByBlockRange'
type MockORM_SelectLogsByBlockRange_Call struct {
	*mock.Call
}

// SelectLogsByBlockRange is a helper method to define mock.On call
//   - ctx context.Context
//   - start int64
//   - end int64
func (_e *MockORM_Expecter) SelectLogsByBlockRange(ctx interface{}, start interface{}, end interface{}) *MockORM_SelectLogsByBlockRange_Call {
	return &MockORM_SelectLogsByBlockRange_Call{Call: _e.mock.On("SelectLogsByBlockRange", ctx, start, end)}
}

func (_c *MockORM_SelectLogsByBlockRange_Call) Run(run func(ctx context.Context, start int64, end int64)) *MockORM_SelectLogsByBlockRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockORM_SelectLogsByBlockRange_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectLogsByBlockRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLogsByBlockRange_Call) RunAndReturn(run func(context.Context, int64, int64) ([]Log, error)) *MockORM_SelectLogsByBlockRange_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLogsCreatedAfter provides a mock function with given fields: ctx, address, eventSig, after, confs
func (_m *MockORM) SelectLogsCreatedAfter(ctx context.Context, address common.Address, eventSig common.Hash, after time.Time, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, after, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectLogsCreatedAfter")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, time.Time, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, after, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, time.Time, types.Confirmations) []Log); ok {
		r0 = rf(ctx, address, eventSig, after, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, time.Time, types.Confirmations) error); ok {
		r1 = rf(ctx, address, eventSig, after, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLogsCreatedAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLogsCreatedAfter'
type MockORM_SelectLogsCreatedAfter_Call struct {
	*mock.Call
}

// SelectLogsCreatedAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - after time.Time
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectLogsCreatedAfter(ctx interface{}, address interface{}, eventSig interface{}, after interface{}, confs interface{}) *MockORM_SelectLogsCreatedAfter_Call {
	return &MockORM_SelectLogsCreatedAfter_Call{Call: _e.mock.On("SelectLogsCreatedAfter", ctx, address, eventSig, after, confs)}
}

func (_c *MockORM_SelectLogsCreatedAfter_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, after time.Time, confs types.Confirmations)) *MockORM_SelectLogsCreatedAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(time.Time), args[4].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectLogsCreatedAfter_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectLogsCreatedAfter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLogsCreatedAfter_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, time.Time, types.Confirmations) ([]Log, error)) *MockORM_SelectLogsCreatedAfter_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLogsDataWordBetween provides a mock function with given fields: ctx, address, eventSig, wordIndexMin, wordIndexMax, wordValue, confs
func (_m *MockORM) SelectLogsDataWordBetween(ctx context.Context, address common.Address, eventSig common.Hash, wordIndexMin int, wordIndexMax int, wordValue common.Hash, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, wordIndexMin, wordIndexMax, wordValue, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectLogsDataWordBetween")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, int, common.Hash, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, wordIndexMin, wordIndexMax, wordValue, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, int, common.Hash, types.Confirmations) []Log); ok {
		r0 = rf(ctx, address, eventSig, wordIndexMin, wordIndexMax, wordValue, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, int, int, common.Hash, types.Confirmations) error); ok {
		r1 = rf(ctx, address, eventSig, wordIndexMin, wordIndexMax, wordValue, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLogsDataWordBetween_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLogsDataWordBetween'
type MockORM_SelectLogsDataWordBetween_Call struct {
	*mock.Call
}

// SelectLogsDataWordBetween is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - wordIndexMin int
//   - wordIndexMax int
//   - wordValue common.Hash
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectLogsDataWordBetween(ctx interface{}, address interface{}, eventSig interface{}, wordIndexMin interface{}, wordIndexMax interface{}, wordValue interface{}, confs interface{}) *MockORM_SelectLogsDataWordBetween_Call {
	return &MockORM_SelectLogsDataWordBetween_Call{Call: _e.mock.On("SelectLogsDataWordBetween", ctx, address, eventSig, wordIndexMin, wordIndexMax, wordValue, confs)}
}

func (_c *MockORM_SelectLogsDataWordBetween_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, wordIndexMin int, wordIndexMax int, wordValue common.Hash, confs types.Confirmations)) *MockORM_SelectLogsDataWordBetween_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(int), args[4].(int), args[5].(common.Hash), args[6].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectLogsDataWordBetween_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectLogsDataWordBetween_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLogsDataWordBetween_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, int, int, common.Hash, types.Confirmations) ([]Log, error)) *MockORM_SelectLogsDataWordBetween_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLogsDataWordGreaterThan provides a mock function with given fields: ctx, address, eventSig, wordIndex, wordValueMin, confs
func (_m *MockORM) SelectLogsDataWordGreaterThan(ctx context.Context, address common.Address, eventSig common.Hash, wordIndex int, wordValueMin common.Hash, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, wordIndex, wordValueMin, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectLogsDataWordGreaterThan")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, common.Hash, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, wordIndex, wordValueMin, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, common.Hash, types.Confirmations) []Log); ok {
		r0 = rf(ctx, address, eventSig, wordIndex, wordValueMin, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, int, common.Hash, types.Confirmations) error); ok {
		r1 = rf(ctx, address, eventSig, wordIndex, wordValueMin, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLogsDataWordGreaterThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLogsDataWordGreaterThan'
type MockORM_SelectLogsDataWordGreaterThan_Call struct {
	*mock.Call
}

// SelectLogsDataWordGreaterThan is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - wordIndex int
//   - wordValueMin common.Hash
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectLogsDataWordGreaterThan(ctx interface{}, address interface{}, eventSig interface{}, wordIndex interface{}, wordValueMin interface{}, confs interface{}) *MockORM_SelectLogsDataWordGreaterThan_Call {
	return &MockORM_SelectLogsDataWordGreaterThan_Call{Call: _e.mock.On("SelectLogsDataWordGreaterThan", ctx, address, eventSig, wordIndex, wordValueMin, confs)}
}

func (_c *MockORM_SelectLogsDataWordGreaterThan_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, wordIndex int, wordValueMin common.Hash, confs types.Confirmations)) *MockORM_SelectLogsDataWordGreaterThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(int), args[4].(common.Hash), args[5].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectLogsDataWordGreaterThan_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectLogsDataWordGreaterThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLogsDataWordGreaterThan_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, int, common.Hash, types.Confirmations) ([]Log, error)) *MockORM_SelectLogsDataWordGreaterThan_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLogsDataWordRange provides a mock function with given fields: ctx, address, eventSig, wordIndex, wordValueMin, wordValueMax, confs
func (_m *MockORM) SelectLogsDataWordRange(ctx context.Context, address common.Address, eventSig common.Hash, wordIndex int, wordValueMin common.Hash, wordValueMax common.Hash, confs types.Confirmations) ([]Log, error) {
	ret := _m.Called(ctx, address, eventSig, wordIndex, wordValueMin, wordValueMax, confs)

	if len(ret) == 0 {
		panic("no return value specified for SelectLogsDataWordRange")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, common.Hash, common.Hash, types.Confirmations) ([]Log, error)); ok {
		return rf(ctx, address, eventSig, wordIndex, wordValueMin, wordValueMax, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash, int, common.Hash, common.Hash, types.Confirmations) []Log); ok {
		r0 = rf(ctx, address, eventSig, wordIndex, wordValueMin, wordValueMax, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash, int, common.Hash, common.Hash, types.Confirmations) error); ok {
		r1 = rf(ctx, address, eventSig, wordIndex, wordValueMin, wordValueMax, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLogsDataWordRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLogsDataWordRange'
type MockORM_SelectLogsDataWordRange_Call struct {
	*mock.Call
}

// SelectLogsDataWordRange is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - eventSig common.Hash
//   - wordIndex int
//   - wordValueMin common.Hash
//   - wordValueMax common.Hash
//   - confs types.Confirmations
func (_e *MockORM_Expecter) SelectLogsDataWordRange(ctx interface{}, address interface{}, eventSig interface{}, wordIndex interface{}, wordValueMin interface{}, wordValueMax interface{}, confs interface{}) *MockORM_SelectLogsDataWordRange_Call {
	return &MockORM_SelectLogsDataWordRange_Call{Call: _e.mock.On("SelectLogsDataWordRange", ctx, address, eventSig, wordIndex, wordValueMin, wordValueMax, confs)}
}

func (_c *MockORM_SelectLogsDataWordRange_Call) Run(run func(ctx context.Context, address common.Address, eventSig common.Hash, wordIndex int, wordValueMin common.Hash, wordValueMax common.Hash, confs types.Confirmations)) *MockORM_SelectLogsDataWordRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash), args[3].(int), args[4].(common.Hash), args[5].(common.Hash), args[6].(types.Confirmations))
	})
	return _c
}

func (_c *MockORM_SelectLogsDataWordRange_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectLogsDataWordRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLogsDataWordRange_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash, int, common.Hash, common.Hash, types.Confirmations) ([]Log, error)) *MockORM_SelectLogsDataWordRange_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLogsWithSigs provides a mock function with given fields: ctx, start, end, address, eventSigs
func (_m *MockORM) SelectLogsWithSigs(ctx context.Context, start int64, end int64, address common.Address, eventSigs []common.Hash) ([]Log, error) {
	ret := _m.Called(ctx, start, end, address, eventSigs)

	if len(ret) == 0 {
		panic("no return value specified for SelectLogsWithSigs")
	}

	var r0 []Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, common.Address, []common.Hash) ([]Log, error)); ok {
		return rf(ctx, start, end, address, eventSigs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, common.Address, []common.Hash) []Log); ok {
		r0 = rf(ctx, start, end, address, eventSigs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, common.Address, []common.Hash) error); ok {
		r1 = rf(ctx, start, end, address, eventSigs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectLogsWithSigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLogsWithSigs'
type MockORM_SelectLogsWithSigs_Call struct {
	*mock.Call
}

// SelectLogsWithSigs is a helper method to define mock.On call
//   - ctx context.Context
//   - start int64
//   - end int64
//   - address common.Address
//   - eventSigs []common.Hash
func (_e *MockORM_Expecter) SelectLogsWithSigs(ctx interface{}, start interface{}, end interface{}, address interface{}, eventSigs interface{}) *MockORM_SelectLogsWithSigs_Call {
	return &MockORM_SelectLogsWithSigs_Call{Call: _e.mock.On("SelectLogsWithSigs", ctx, start, end, address, eventSigs)}
}

func (_c *MockORM_SelectLogsWithSigs_Call) Run(run func(ctx context.Context, start int64, end int64, address common.Address, eventSigs []common.Hash)) *MockORM_SelectLogsWithSigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(common.Address), args[4].([]common.Hash))
	})
	return _c
}

func (_c *MockORM_SelectLogsWithSigs_Call) Return(_a0 []Log, _a1 error) *MockORM_SelectLogsWithSigs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectLogsWithSigs_Call) RunAndReturn(run func(context.Context, int64, int64, common.Address, []common.Hash) ([]Log, error)) *MockORM_SelectLogsWithSigs_Call {
	_c.Call.Return(run)
	return _c
}

// SelectNewestBlock provides a mock function with given fields: ctx, maxAllowedBlockNumber
func (_m *MockORM) SelectNewestBlock(ctx context.Context, maxAllowedBlockNumber int64) (*Block, error) {
	ret := _m.Called(ctx, maxAllowedBlockNumber)

	if len(ret) == 0 {
		panic("no return value specified for SelectNewestBlock")
	}

	var r0 *Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*Block, error)); ok {
		return rf(ctx, maxAllowedBlockNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *Block); ok {
		r0 = rf(ctx, maxAllowedBlockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, maxAllowedBlockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectNewestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectNewestBlock'
type MockORM_SelectNewestBlock_Call struct {
	*mock.Call
}

// SelectNewestBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - maxAllowedBlockNumber int64
func (_e *MockORM_Expecter) SelectNewestBlock(ctx interface{}, maxAllowedBlockNumber interface{}) *MockORM_SelectNewestBlock_Call {
	return &MockORM_SelectNewestBlock_Call{Call: _e.mock.On("SelectNewestBlock", ctx, maxAllowedBlockNumber)}
}

func (_c *MockORM_SelectNewestBlock_Call) Run(run func(ctx context.Context, maxAllowedBlockNumber int64)) *MockORM_SelectNewestBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockORM_SelectNewestBlock_Call) Return(_a0 *Block, _a1 error) *MockORM_SelectNewestBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectNewestBlock_Call) RunAndReturn(run func(context.Context, int64) (*Block, error)) *MockORM_SelectNewestBlock_Call {
	_c.Call.Return(run)
	return _c
}

// SelectOldestBlock provides a mock function with given fields: ctx, minAllowedBlockNumber
func (_m *MockORM) SelectOldestBlock(ctx context.Context, minAllowedBlockNumber int64) (*Block, error) {
	ret := _m.Called(ctx, minAllowedBlockNumber)

	if len(ret) == 0 {
		panic("no return value specified for SelectOldestBlock")
	}

	var r0 *Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*Block, error)); ok {
		return rf(ctx, minAllowedBlockNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *Block); ok {
		r0 = rf(ctx, minAllowedBlockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, minAllowedBlockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectOldestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectOldestBlock'
type MockORM_SelectOldestBlock_Call struct {
	*mock.Call
}

// SelectOldestBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - minAllowedBlockNumber int64
func (_e *MockORM_Expecter) SelectOldestBlock(ctx interface{}, minAllowedBlockNumber interface{}) *MockORM_SelectOldestBlock_Call {
	return &MockORM_SelectOldestBlock_Call{Call: _e.mock.On("SelectOldestBlock", ctx, minAllowedBlockNumber)}
}

func (_c *MockORM_SelectOldestBlock_Call) Run(run func(ctx context.Context, minAllowedBlockNumber int64)) *MockORM_SelectOldestBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockORM_SelectOldestBlock_Call) Return(_a0 *Block, _a1 error) *MockORM_SelectOldestBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockORM_SelectOldestBlock_Call) RunAndReturn(run func(context.Context, int64) (*Block, error)) *MockORM_SelectOldestBlock_Call {
	_c.Call.Return(run)
	return _c
}

// SelectUnmatchedLogIDs provides a mock function with given fields: ctx, limit
func (_m *MockORM) SelectUnmatchedLogIDs(ctx context.Context, limit int64) ([]uint64, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for SelectUnmatchedLogIDs")
	}

	var r0 []uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]uint64, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []uint64); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockORM_SelectUnmatchedLogIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectUnmatchedLogIDs'
type MockORM_SelectUnmatchedLogIDs_Call struct {
	*mock.Call
}

// SelectUnmatchedLogIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
func (_e *MockORM_Expecter) SelectUnmatchedLogIDs(ctx interface{}, limit interface{}) *MockORM_SelectUnmatchedLogIDs_Call {
	return &MockORM_SelectUnmatchedLogIDs_Call{Call: _e.mock.On("SelectUnmatchedLogIDs", ctx, limit)}
}

func (_c *MockORM_SelectUnmatchedLogIDs_Call) Run(run func(ctx context.Context, limit int64)) *MockORM_SelectUnmatchedLogIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockORM_SelectUnmatchedLogIDs_Call) Return(ids []uint64, err error) *MockORM_SelectUnmatchedLogIDs_Call {
	_c.Call.Return(ids, err)
	return _c
}

func (_c *MockORM_SelectUnmatchedLogIDs_Call) RunAndReturn(run func(context.Context, int64) ([]uint64, error)) *MockORM_SelectUnmatchedLogIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockORM creates a new instance of MockORM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockORM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockORM {
	mock := &MockORM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
