// SPDX-License-Identifier: BUSL 1.1
pragma solidity 0.8.24;

import {Ownable2StepMsgSender} from "../../shared/access/Ownable2StepMsgSender.sol";

import {ECDSA} from "../../vendor/openzeppelin-solidity/v5.0.2/contracts/utils/cryptography/ECDSA.sol";
import {MessageHashUtils} from
  "../../vendor/openzeppelin-solidity/v5.0.2/contracts/utils/cryptography/MessageHashUtils.sol";
import {EnumerableSet} from "../../vendor/openzeppelin-solidity/v5.0.2/contracts/utils/structs/EnumerableSet.sol";

/// @title OwnershipLink
/// @notice This contract allows the transaction senders to submit ownership proofs for linking and unlinking their address.
/// @dev Ownership proofs are signed messages generated by an external entity, with each proof being unique for each owner
/// address. The owner address is embedded into the proof itself together with other metadata representing a unique account.
/// A legitimate assumption is that only a person (or a group of people) who has access to the private key of the owner
/// address and valid signature signed by the external entity can "unlock" the ownership proof and submit it to this contract.
abstract contract OwnershipLink is Ownable2StepMsgSender {
  using EnumerableSet for EnumerableSet.AddressSet;

  mapping(address signer => bool allowed) private s_allowedSigners;
  EnumerableSet.AddressSet private s_linkedOwners;

  event AllowedSignersUpdatedV1(address[] signers, bool allowed);
  event OwnershipLinkUpdatedV1(address indexed owner, bytes32 indexed proof, bool indexed added);

  error LinkOwnerRequestExpired(address caller, uint256 currentTime, uint256 expiryTimestamp);
  error UnlinkOwnerRequestExpired(address caller, uint256 currentTime, uint256 expiryTimestamp);
  error OwnershipLinkAlreadyExists(address owner);
  error OwnershipLinkDoesNotExist(address owner);
  error InvalidSignature(bytes signature, uint8 recoverErrorId, bytes32 recoverErrorArg);
  error InvalidSValue(bytes signature, bytes32 s);
  error InvalidVValue(bytes signature, uint8 v);
  error InvalidOwnershipLink(address owner, uint256 validityTimestamp, bytes32 proof, bytes signature);

  /// @notice Modifier to check if the ownership proof is submitted by the transaction sender and its owner address is linked.
  /// @dev This modifier can be used to restrict access to functions in the derived contract that require
  // the ownership proof to be submitted. If the ownership proof is not submitted, the transaction will revert.
  modifier hasOwnerLinked() {
    if (!s_linkedOwners.contains(msg.sender)) {
      revert OwnershipLinkDoesNotExist(msg.sender);
    }
    _;
  }

  /// @notice Sets the allowed signers for ownership proofs.
  /// @param signers The addresses of the signers
  /// @param allowed The boolean value indicating whether the signer is allowed or not
  /// @dev Ownership proofs can only be signed by approved group of signers.
  /// When submitting signed proof to this contract, if recovered signature doesn't match any of the signers,
  /// it will be rejected.
  function updateAllowedSigners(address[] calldata signers, bool allowed) external onlyOwner {
    for (uint256 i = 0; i < signers.length; ++i) {
      s_allowedSigners[signers[i]] = allowed;
    }
    emit AllowedSignersUpdatedV1(signers, allowed);
  }

  /// @notice Returns the allowed signer for ownership proofs.
  /// @param signer The address of the signer
  /// @return The boolean value indicating whether the signer is allowed to sign ownership proofs or not
  function isAllowedSigner(
    address signer
  ) external view returns (bool) {
    return s_allowedSigners[signer];
  }

  /// @notice View function to verify if the linkOwner() function can be called successfully.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev This function is used to verify if the ownership proof is valid without actually linking the owner address.
  /// It will revert if the validation process fails at any point (expired request, already linked owner, invalid signature).
  function tryLinkOwner(uint256 validityTimestamp, bytes32 proof, bytes calldata signature) public view {
    if (block.timestamp > validityTimestamp) {
      revert LinkOwnerRequestExpired(msg.sender, block.timestamp, validityTimestamp);
    }

    if (s_linkedOwners.contains(msg.sender)) {
      revert OwnershipLinkAlreadyExists(msg.sender);
    }

    address signer = _recoverSigner(validityTimestamp, proof, signature);
    if (!s_allowedSigners[signer]) {
      revert InvalidOwnershipLink(msg.sender, validityTimestamp, proof, signature);
    }
  }

  /// @notice Transaction sender submits ownership proof for verification and approval. Upon approval, owner is linked.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev The ownership proof is a hash of the ownership proof metadata, which is signed by the allowed signer.
  /// The ownership proof metadata is a combination of the claimed owner address, validity timestamp, and the proof hash.
  /// Request will be rejected if the validity timestamp has expired or if the proof has already been submitted (by this
  /// transaction sender or a different one).
  /// If the transaction sender is truly the owner of the claimed address, the proof will be acccepted if the
  /// signature is valid and recoverable signer matches any of the allowed signers.
  function linkOwner(uint256 validityTimestamp, bytes32 proof, bytes calldata signature) external {
    tryLinkOwner(validityTimestamp, proof, signature);

    s_linkedOwners.add(msg.sender);
    emit OwnershipLinkUpdatedV1(msg.sender, proof, true);
  }

  /// @notice View function to verify if the unlinkOwner() function can be called successfully.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev This function is used to verify if the ownership proof is valid without actually unlinked the owner address.
  /// It will revert if the validation process fails at any point (expired request, not linked owner, invalid signature).
  function tryUnlinkOwner(uint256 validityTimestamp, bytes32 proof, bytes calldata signature) public view {
    if (block.timestamp > validityTimestamp) {
      revert UnlinkOwnerRequestExpired(msg.sender, block.timestamp, validityTimestamp);
    }

    if (!s_linkedOwners.contains(msg.sender)) {
      revert OwnershipLinkDoesNotExist(msg.sender);
    }

    address signer = _recoverSigner(validityTimestamp, proof, signature);
    if (!s_allowedSigners[signer]) {
      revert InvalidOwnershipLink(msg.sender, validityTimestamp, proof, signature);
    }
  }

  /// @notice Transaction sender submits ownership proof for verification and approval. Upon approval, owner is unlinked.
  /// @param validityTimestamp Validity of the ownership proof.
  /// @param proof The ownership proof to be submitted.
  /// @param signature The signature of the ownership proof metadata.
  /// @dev The ownership proof is a hash of the ownership proof metadata, which is signed by the allowed signer.
  /// The ownership proof metadata is a combination of the claimed owner address, validity timestamp, and the proof hash.
  /// Request will be rejected if the validity timestamp has expired or if the proof hasn't been submitted by this
  /// transaction sender (can't unlink a different owner).
  /// If the transaction sender is truly the owner of the claimed address, the proof will be accepted if the
  /// signature is valid and recoverable signer matches any of the allowed signers.
  function unlinkOwner(uint256 validityTimestamp, bytes32 proof, bytes calldata signature) external {
    tryUnlinkOwner(validityTimestamp, proof, signature);

    s_linkedOwners.remove(msg.sender);
    emit OwnershipLinkUpdatedV1(msg.sender, proof, false);
  }

  /// @notice Admin removes ownership proof for the given owner and unlinks the owner address.
  /// @param owner The address of the owner
  /// @dev This function can only be called by the contract owner. It will remove the ownership proof for the given
  /// owner and skip verification process. It should only be used in case of emergency if the owner has lost
  /// access to the private key and can't complete the unlinking themselves.
  function adminUnlinkOwner(
    address owner
  ) external onlyOwner {
    if (!s_linkedOwners.contains(owner)) {
      revert OwnershipLinkDoesNotExist(owner);
    }

    s_linkedOwners.remove(owner);
    emit OwnershipLinkUpdatedV1(owner, bytes32(0), false);
  }

  //// @notice Returns if the ownership proof is submitted for the given owner.
  /// @param owner The address of the owner
  /// @return True if the ownership proof is submitted, false otherwise
  function isOwnerLinked(
    address owner
  ) external view returns (bool) {
    return s_linkedOwners.contains(owner);
  }

  /// @notice Returns a list of linked owner for the given range.
  /// @param start The starting index of the range
  /// @param batchSize The size of the batch to return (be vary of using a reasonable value here)
  /// @return A list of linked owners
  /// @dev The function will return a list of addresses of owners who have submitted ownership proofs in the
  /// order in which they were submitted.
  /// The function will return an empty list if the start index is greater than the total number of owners.
  /// @notice List of owners may change between subsequent calls to this function. It is recommend to call this
  /// function by anchoring a specific block number to ensure the list of owners is immutable between subsequent calls.
  function getLinkedOwners(uint256 start, uint256 batchSize) external view returns (address[] memory) {
    uint256 total = s_linkedOwners.length();
    if (start >= total) {
      return new address[](0);
    }

    uint256 end = (start + batchSize > total) ? total : start + batchSize;
    uint256 length = end - start;
    address[] memory owners = new address[](length);

    for (uint256 i = 0; i < length; ++i) {
      owners[i] = s_linkedOwners.at(start + i);
    }

    return owners;
  }

  /// @notice Returns the signer of the recovered signature or revert.
  /// @param validityTimestamp The validity timestamp of the ownership proof.
  /// @param proof The ownership proof.
  /// @param signature The signature of the ownership proof metadata.
  /// @return The signer of the recovered signature.
  /// @dev The function tries to re-generate the message digest based on the provided parameters and by following
  /// EIP-191. The it will try to recover the signer address. The function will revert if the signature is invalid.
  function _recoverSigner(
    uint256 validityTimestamp,
    bytes32 proof,
    bytes memory signature
  ) internal view returns (address) {
    // Follow EIP-191 for recoverable signatures
    bytes32 messageHash = keccak256(abi.encodePacked(msg.sender, block.chainid, validityTimestamp, proof));
    bytes32 prefixedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);

    (address signer, ECDSA.RecoverError err, bytes32 errArg) = ECDSA.tryRecover(prefixedMessageHash, signature);
    if (err != ECDSA.RecoverError.NoError) {
      revert InvalidSignature(signature, uint8(err), errArg);
    }

    return signer;
  }
}
