package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/smartcontractkit/chainlink-evm/gethwrappers"
)

const template = `// Code generated by gethwrappers/zksync. DO NOT EDIT.
package %s

func Deploy%sZkSync() {
	println("Deploying contract on ZkSync")
}
`

func main() {
	project := os.Args[1]
	contractName := os.Args[2]
	packageName := os.Args[3]

	fmt.Println("Generating", packageName, "contract wrapper")

	cwd, err := os.Getwd() // gethwrappers/zksync directory
	if err != nil {
		gethwrappers.Exit("could not get working directory", err)
	}
	outDir := filepath.Join(cwd, "..", project, "generated", packageName)
	if mkdErr := os.MkdirAll(outDir, 0700); err != nil {
		gethwrappers.Exit("failed to create wrapper dir", mkdErr)
	}
	outPath := filepath.Join(outDir, packageName+"_zksync.go")

	// sample generation
	data := []byte(fmt.Sprintf(template, packageName, contractName))

	err = os.WriteFile(outPath, data, 0600)
	if err != nil {
		gethwrappers.Exit("failed to write file", err)
	}
}
