package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/smartcontractkit/chainlink-evm/gethwrappers"
	zksyncwrapper "github.com/smartcontractkit/chainlink-evm/gethwrappers/generation/generate/zksync"
)

const template = `// Code generated by gethwrappers/zksync. DO NOT EDIT.
package %s

func Deploy%sZkSync() {
	println("Deploying contract on ZkSync")
}
`

func main() {
	project := os.Args[1]
	contractName := os.Args[2]
	packageName := os.Args[3]

	fmt.Println("Generating", packageName, "contract wrapper")

	cwd, err := os.Getwd() // gethwrappers/zksync directory
	if err != nil {
		gethwrappers.Exit("could not get working directory", err)
	}

	zksyncBytecodePath := filepath.Join(cwd, "..", "..", "contracts", "zkout", contractName+".sol", contractName+".json")
	outPath := filepath.Join(cwd, "..", project, "generated", packageName, packageName+"_zksync.go")

	zksyncwrapper.WrapZksyncDeploy(zksyncBytecodePath, contractName, packageName, outPath)
}
