// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LimitJobType is an autogenerated mock type for the LimitJobType type
type LimitJobType struct {
	mock.Mock
}

type LimitJobType_Expecter struct {
	mock *mock.Mock
}

func (_m *LimitJobType) EXPECT() *LimitJobType_Expecter {
	return &LimitJobType_Expecter{mock: &_m.Mock}
}

// DR provides a mock function with no fields
func (_m *LimitJobType) DR() *uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DR")
	}

	var r0 *uint32
	if rf, ok := ret.Get(0).(func() *uint32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint32)
		}
	}

	return r0
}

// LimitJobType_DR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DR'
type LimitJobType_DR_Call struct {
	*mock.Call
}

// DR is a helper method to define mock.On call
func (_e *LimitJobType_Expecter) DR() *LimitJobType_DR_Call {
	return &LimitJobType_DR_Call{Call: _e.mock.On("DR")}
}

func (_c *LimitJobType_DR_Call) Run(run func()) *LimitJobType_DR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LimitJobType_DR_Call) Return(_a0 *uint32) *LimitJobType_DR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LimitJobType_DR_Call) RunAndReturn(run func() *uint32) *LimitJobType_DR_Call {
	_c.Call.Return(run)
	return _c
}

// FM provides a mock function with no fields
func (_m *LimitJobType) FM() *uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FM")
	}

	var r0 *uint32
	if rf, ok := ret.Get(0).(func() *uint32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint32)
		}
	}

	return r0
}

// LimitJobType_FM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FM'
type LimitJobType_FM_Call struct {
	*mock.Call
}

// FM is a helper method to define mock.On call
func (_e *LimitJobType_Expecter) FM() *LimitJobType_FM_Call {
	return &LimitJobType_FM_Call{Call: _e.mock.On("FM")}
}

func (_c *LimitJobType_FM_Call) Run(run func()) *LimitJobType_FM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LimitJobType_FM_Call) Return(_a0 *uint32) *LimitJobType_FM_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LimitJobType_FM_Call) RunAndReturn(run func() *uint32) *LimitJobType_FM_Call {
	_c.Call.Return(run)
	return _c
}

// Keeper provides a mock function with no fields
func (_m *LimitJobType) Keeper() *uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keeper")
	}

	var r0 *uint32
	if rf, ok := ret.Get(0).(func() *uint32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint32)
		}
	}

	return r0
}

// LimitJobType_Keeper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keeper'
type LimitJobType_Keeper_Call struct {
	*mock.Call
}

// Keeper is a helper method to define mock.On call
func (_e *LimitJobType_Expecter) Keeper() *LimitJobType_Keeper_Call {
	return &LimitJobType_Keeper_Call{Call: _e.mock.On("Keeper")}
}

func (_c *LimitJobType_Keeper_Call) Run(run func()) *LimitJobType_Keeper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LimitJobType_Keeper_Call) Return(_a0 *uint32) *LimitJobType_Keeper_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LimitJobType_Keeper_Call) RunAndReturn(run func() *uint32) *LimitJobType_Keeper_Call {
	_c.Call.Return(run)
	return _c
}

// OCR provides a mock function with no fields
func (_m *LimitJobType) OCR() *uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OCR")
	}

	var r0 *uint32
	if rf, ok := ret.Get(0).(func() *uint32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint32)
		}
	}

	return r0
}

// LimitJobType_OCR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OCR'
type LimitJobType_OCR_Call struct {
	*mock.Call
}

// OCR is a helper method to define mock.On call
func (_e *LimitJobType_Expecter) OCR() *LimitJobType_OCR_Call {
	return &LimitJobType_OCR_Call{Call: _e.mock.On("OCR")}
}

func (_c *LimitJobType_OCR_Call) Run(run func()) *LimitJobType_OCR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LimitJobType_OCR_Call) Return(_a0 *uint32) *LimitJobType_OCR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LimitJobType_OCR_Call) RunAndReturn(run func() *uint32) *LimitJobType_OCR_Call {
	_c.Call.Return(run)
	return _c
}

// OCR2 provides a mock function with no fields
func (_m *LimitJobType) OCR2() *uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OCR2")
	}

	var r0 *uint32
	if rf, ok := ret.Get(0).(func() *uint32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint32)
		}
	}

	return r0
}

// LimitJobType_OCR2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OCR2'
type LimitJobType_OCR2_Call struct {
	*mock.Call
}

// OCR2 is a helper method to define mock.On call
func (_e *LimitJobType_Expecter) OCR2() *LimitJobType_OCR2_Call {
	return &LimitJobType_OCR2_Call{Call: _e.mock.On("OCR2")}
}

func (_c *LimitJobType_OCR2_Call) Run(run func()) *LimitJobType_OCR2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LimitJobType_OCR2_Call) Return(_a0 *uint32) *LimitJobType_OCR2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LimitJobType_OCR2_Call) RunAndReturn(run func() *uint32) *LimitJobType_OCR2_Call {
	_c.Call.Return(run)
	return _c
}

// VRF provides a mock function with no fields
func (_m *LimitJobType) VRF() *uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VRF")
	}

	var r0 *uint32
	if rf, ok := ret.Get(0).(func() *uint32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint32)
		}
	}

	return r0
}

// LimitJobType_VRF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VRF'
type LimitJobType_VRF_Call struct {
	*mock.Call
}

// VRF is a helper method to define mock.On call
func (_e *LimitJobType_Expecter) VRF() *LimitJobType_VRF_Call {
	return &LimitJobType_VRF_Call{Call: _e.mock.On("VRF")}
}

func (_c *LimitJobType_VRF_Call) Run(run func()) *LimitJobType_VRF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LimitJobType_VRF_Call) Return(_a0 *uint32) *LimitJobType_VRF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LimitJobType_VRF_Call) RunAndReturn(run func() *uint32) *LimitJobType_VRF_Call {
	_c.Call.Return(run)
	return _c
}

// NewLimitJobType creates a new instance of LimitJobType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLimitJobType(t interface {
	mock.TestingT
	Cleanup(func())
}) *LimitJobType {
	mock := &LimitJobType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
