name: Run golangci-lint

on: [pull_request]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Setup tar default options
        shell: bash
        # Do not overwrite existing files when extracting files from a cache archive.
        # Since actions/cache does not support this option, we set it here as a default.
        run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: go.sum
          go-version-file: go.mod

      - name: Run golangci-lint
        if: ${{ always() && !contains(join(github.event.pull_request.labels.*.name, ' '), 'allow-lint-issues') }}
        # v7.0.0
        uses: golangci/golangci-lint-action@7119f3d5ddced62a10a044847a6c6bb0f7a5e76a
        with:
          args: --config=${{ github.workspace }}/.golangci.yml
          only-new-issues: true
          version: v2.4.0
          working-directory: pkg